#!/usr/bin/env bash
# tests/smoke.sh — end-to-end smoke test for ck-code's scripts/bin against a
# synthetic, throwaway v6 project fixture.
#
# Builds a temp git repo with a v6 tasks/ layout (see references/data-model.md),
# puts this plugin's bin/ on PATH, and drives the real scripts against it: ck-index,
# ck-view, ck-doctor, ck-story, ck-bootstrap, and the four hook scripts. Assertions
# encode the CORRECT behaviour per references/data-model.md, references/stories-index.md,
# references/feature-index.md and skills/build/references/wave-mode.md — a FAIL here is
# not necessarily this harness being wrong; see tests/README.md.
#
# bash 3.2 compatible: no mapfile, no associative arrays, no ${var,,}. No external
# deps beyond git, awk, sed, python3; jq-dependent assertions are skipped (with a
# note) when jq is not on PATH.

set -uo pipefail

PLUGIN_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)"
FIXTURE=""
PASS=0
FAIL=0

cleanup() {
  [ -n "$FIXTURE" ] && [ -d "$FIXTURE" ] && rm -rf "$FIXTURE"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

# ---- tiny assertion harness ---------------------------------------------------

log_ok() {
  printf 'ok      %s\n' "$1"
  PASS=$((PASS + 1))
}
log_fail() {
  printf 'FAIL    %s\n' "$1"
  [ -n "${2:-}" ] && printf '        %s\n' "$2" | sed 's/^/        /' | sed '1s/^        //'
  FAIL=$((FAIL + 1))
}
log_skip() {
  printf 'skip    %s\n' "$1"
}

assert_contains() { # label haystack needle
  case "$2" in
    *"$3"*) log_ok "$1" ;;
    *) log_fail "$1" "expected to contain: $3" ;;
  esac
}
assert_not_contains() { # label haystack needle
  case "$2" in
    *"$3"*) log_fail "$1" "expected NOT to contain: $3" ;;
    *) log_ok "$1" ;;
  esac
}
assert_eq() { # label want got
  [ "$2" = "$3" ] && log_ok "$1" || log_fail "$1" "expected [$2] got [$3]"
}
assert_exit() { # label want_code got_code
  [ "$2" = "$3" ] && log_ok "$1" || log_fail "$1" "expected exit $2, got $3"
}
assert_true() { # label condition-as-string(0/1)
  [ "$2" -eq 0 ] && log_ok "$1" || log_fail "$1" "condition failed"
}

# ---- fixture construction ------------------------------------------------------
# tasks/<slug>/epics/NN_<epic-slug>/stories/SS_<story-slug>.md — v7 layout
# (references/data-model.md). One plan (2026-01-01_demo) with two epics; a second,
# deliberately-broken plan is added later to exercise ck-doctor scoping / ck-story
# WARN passthrough.

write_epic() { # write_epic PATH EPIC SLUG TITLE DESCRIPTION
  mkdir -p "$(dirname "$1")"
  cat > "$1" <<EOF
---
epic: $2
slug: $3
title: $4
description: $5
issue:
pr:
delivery:
---

# Epic $2: $4

## Description

$5.

## Goals

- Ship $4.

## Scope

### In Scope

- Everything under this epic's stories.

### Out of Scope

- Nothing noted.

## Acceptance Criteria

- [ ] All stories in this epic are done.
EOF
}

# write_story PATH ID TITLE EPIC STATUS SIZE BLOCKED FILES ISSUE PR DELIVERY PRIOR [BODY_EXTRA]
write_story() {
  mkdir -p "$(dirname "$1")"
  cat > "$1" <<EOF
---
id: $2
title: $3
epic: $4
status: $5
size: $6
blocked_by: $7
files: $8
issue: $9
pr: ${10}
delivery: ${11}
prior_status: ${12}
---

# Story $2: $3

## Description

Fixture story for ck-code's smoke test.

## Acceptance Criteria

- [ ] Fixture criterion one.
- [ ] Fixture criterion two.

## Implementation Tasks

- [ ] Fixture task.

## Technical Notes

None.
EOF
  if [ -n "${13:-}" ]; then
    printf '\n%s\n' "${13}" >> "$1"
  fi
}

build_fixture() {
  mkdir -p tasks
  cat > tasks/VERSION.md <<'EOF'
<!-- AUTO-GENERATED by ck-code. DO NOT EDIT BY HAND. -->

layout: v7
requires: ck-code >= 7.0.0
EOF

  mkdir -p "tasks/2026-01-01_demo"
  cat > "tasks/2026-01-01_demo/OVERVIEW.md" <<'EOF'
---
slug: demo
title: Demo Project
integration: story
branch:
issue:
pr:
delivery:
---

# Demo Project

## Vision

Fixture project used only by ck-code's tests/smoke.sh.

## Architecture

N/A — fixture only.

## Tech Stack

| Layer | Technology | Version |
| ----- | ---------- | ------- |
| n/a   | n/a        | n/a     |

## Components

### Fixture

- **Purpose:** exercise ck-index/ck-view/ck-doctor/ck-story against a real v6 layout.

## Key Design Decisions

- None — this is a fixture.

## Non-Functional Requirements

- **Performance:** n/a
- **Security:** n/a
- **Compatibility:** n/a

## References

- Generated: by tests/smoke.sh
EOF
  cat > "tasks/2026-01-01_demo/ROADMAP.md" <<'EOF'
# Roadmap

## Milestones

| Milestone | Epics | Target |
|-----------|-------|--------|
| MVP       | 01, 02 | n/a |
EOF

  write_epic "tasks/2026-01-01_demo/epics/01_foundation/EPIC.md" 01 foundation Foundation \
    "Core foundation work"
  write_epic "tasks/2026-01-01_demo/epics/02_payments/EPIC.md" 02 payments Payments \
    "Payment processing"

  # ---- epic 01: foundation ----
  write_story "tasks/2026-01-01_demo/epics/01_foundation/stories/01_bootstrap.md" \
    01-01 "Bootstrap project scaffold" 01 done S "[]" "[src/app.ts]" "" 10 merged ""
  write_story "tasks/2026-01-01_demo/epics/01_foundation/stories/02_ci-pipeline.md" \
    01-02 "Set up CI pipeline" 01 done S "[01-01]" "[.github/workflows/ci.yml]" "" "" direct ""
  write_story "tasks/2026-01-01_demo/epics/01_foundation/stories/03_login-fix.md" \
    01-03 'Fix "login" bug | urgent case' 01 in-progress M "[01-02]" "[src/auth/login.ts]" "" "" "" ""

  # ---- epic 02: payments ----
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/01_charge.md" \
    02-01 "Charge processing" 02 done S "[]" "[src/payments/charge.ts]" "" "" "" ""
  # blocked_by quoted ON PURPOSE — references/data-model.md's inline-flow-list contract
  # allows a quoted scalar; ck-index must unquote it in the STORIES_INDEX cell.
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/02_refund.md" \
    02-02 "Refund handling" 02 todo S '["02-01"]' "[src/payments/refund.ts]" "" "" "" ""
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/03_invoice.md" \
    02-03 "Invoice generation" 02 todo S "[02-02]" "[src/payments/invoice.ts]" "" "" "" ""
  # out-of-epic blocker (01-03, epic 01), not done — must render UNSCHEDULABLE in
  # `ck-view waves --epic 02` (skills/build/references/wave-mode.md).
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/04_receipt.md" \
    02-04 "Receipt email" 02 todo S "[01-03]" "[src/payments/receipt.ts]" "" "" "" ""
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/05_webhook.md" \
    02-05 "Webhook retries" 02 skip S "[]" "[src/payments/webhook.ts]" "" "" "" ""
  # bug with a prior_status, and the required "## Bug Report" body section so
  # ck-doctor's check_stories does not flag it on the clean fixture.
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/06_double-charge.md" \
    02-06 "Fix double-charge bug" 02 bug S "[]" "[src/payments/charge.ts]" "" "" "" done \
    $'## Bug Report\n\nCustomers were double-charged under a race condition.'
  # files overlap with 02-02 (src/payments/refund.ts) — the wave splitter must not
  # put both in the same wave even though both are otherwise wave-1 ready.
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/07_export.md" \
    02-07 "Export refunds report" 02 todo S "[]" "[src/payments/refund.ts, src/payments/export.ts]" "" "" "" ""
  # blocked ONLY by 02-05, which is `skip` — a skipped blocker releases its dependants,
  # so this story is ready in ck-view, Todo on the board, and clean in ck-doctor.
  write_story "tasks/2026-01-01_demo/epics/02_payments/stories/08_audit.md" \
    02-08 "Audit log" 02 todo S "[02-05]" "[src/payments/audit.ts]" 58 "" "" ""

  printf '%s\n' "# Generated by ck-code." "STORIES_INDEX.md" "EPICS_INDEX.md" > tasks/.gitignore

  git init -q .
  git symbolic-ref HEAD refs/heads/main
  git config user.email "smoke@ck-code.test"
  git config user.name "ck-code smoke"
  git add -A
  git commit -q -m "fixture: v7 demo project"
  git checkout -q -b story/01-03-login-fix
}

add_broken_plan() {
  mkdir -p "tasks/2026-02-02_other/epics/03_other/stories"
  cat > "tasks/2026-02-02_other/OVERVIEW.md" <<'EOF'
---
slug: other
title: Other Project
integration: story
---

# Other Project

## Vision

Second, deliberately-broken plan — exercises ck-doctor plan scoping and
ck-story's WARN passthrough.
EOF
  write_epic "tasks/2026-02-02_other/epics/03_other/EPIC.md" 03 other Other "Other work"
  # Missing `id:` on purpose — ck-index must skip it with a WARN, and ck-doctor's
  # check_stories must flag it as an ERROR.
  cat > "tasks/2026-02-02_other/epics/03_other/stories/01_broken.md" <<'EOF'
---
id:
title: Broken story
epic: 03
status: todo
size: S
blocked_by: []
files: []
issue:
pr:
delivery:
prior_status:
---

# Story: Broken story

## Description

Missing `id:` on purpose.
EOF
  git add -A
  git commit -q -m "fixture: add broken plan (missing id)"
}

# ---- go -------------------------------------------------------------------

echo "=== layout constants agree ==="
L_GATE=$(awk '/^LAYOUT[ \t]*=/{print $NF; exit}' "$PLUGIN_ROOT/references/version-gate.md")
L_HOOK=$(awk -F= '/^LAYOUT=/{print $2; exit}' "$PLUGIN_ROOT/scripts/session-start.sh")
L_DOC=$(awk -F'"' '/^FALLBACK_LAYOUT=/{print $2; exit}' "$PLUGIN_ROOT/scripts/ck-doctor.sh")
assert_eq "LAYOUT: session-start.sh matches version-gate.md" "$L_GATE" "$L_HOOK"
assert_eq "LAYOUT: ck-doctor.sh matches version-gate.md" "$L_GATE" "$L_DOC"
MIN_GATE=$(awk '/^MIN_PLUGIN[ \t]*=/{print $NF; exit}' "$PLUGIN_ROOT/references/version-gate.md")
PLUGIN_V=$(awk -F'"' '/"version"[[:space:]]*:/{print $4; exit}' "$PLUGIN_ROOT/.claude-plugin/plugin.json")
# shellcheck source=scripts/lib/ck-common.sh
. "$PLUGIN_ROOT/scripts/lib/ck-common.sh"
if ck_version_lt "$PLUGIN_V" "$MIN_GATE"; then
  log_fail "plugin.json version ($PLUGIN_V) reads the layout it requires (MIN_PLUGIN $MIN_GATE)" "bump plugin.json or MIN_PLUGIN"
else
  log_ok "plugin.json version ($PLUGIN_V) reads the layout it requires (MIN_PLUGIN $MIN_GATE)"
fi
assert_true "ck_version_lt: 7.0.9 < 7.0.10" "$(ck_version_lt 7.0.9 7.0.10; echo $?)"
assert_true "ck_version_lt: 7.1.0 is not < 7.0.10" "$([ "$(ck_version_lt 7.1.0 7.0.10; echo $?)" -ne 0 ]; echo $?)"
echo

FIXTURE="$(mktemp -d 2>/dev/null || mktemp -d -t ckcode-smoke)"
( cd "$FIXTURE" && build_fixture )

export PATH="$PLUGIN_ROOT/bin:$PATH"

HAVE_JQ=1
command -v jq >/dev/null 2>&1 || HAVE_JQ=0

cd "$FIXTURE" || { echo "smoke: could not cd into fixture $FIXTURE" >&2; exit 1; }

echo "=== ck-index (first run) ==="
IDX_OUT=$(ck-index 2>&1); IDX_RC=$?
assert_exit "ck-index: exits 0 on the clean fixture" 0 "$IDX_RC"
assert_not_contains "ck-index: no WARN on the clean fixture" "$IDX_OUT" "ck-index: WARN"

SI_DEMO="tasks/2026-01-01_demo/STORIES_INDEX.md"
FI="tasks/EPICS_INDEX.md"
assert_true "ck-index: wrote $SI_DEMO" "$([ -f "$SI_DEMO" ]; echo $?)"
assert_true "ck-index: wrote $FI" "$([ -f "$FI" ]; echo $?)"

echo
echo "=== ck-index idempotency ==="
cp "$SI_DEMO" "$FIXTURE/.snap_si"
cp "$FI" "$FIXTURE/.snap_fi"
ck-index >/dev/null 2>&1
if diff -q "$SI_DEMO" "$FIXTURE/.snap_si" >/dev/null 2>&1; then
  log_ok "ck-index: STORIES_INDEX.md byte-identical across two runs"
else
  log_fail "ck-index: STORIES_INDEX.md byte-identical across two runs" "$(diff "$SI_DEMO" "$FIXTURE/.snap_si" | head -10)"
fi
if diff -q "$FI" "$FIXTURE/.snap_fi" >/dev/null 2>&1; then
  log_ok "ck-index: EPICS_INDEX.md byte-identical across two runs"
else
  log_fail "ck-index: EPICS_INDEX.md byte-identical across two runs" "$(diff "$FI" "$FIXTURE/.snap_fi" | head -10)"
fi
rm -f "$FIXTURE/.snap_si" "$FIXTURE/.snap_fi"

echo
echo "=== STORIES_INDEX content ==="
# Match on the ID column specifically (field 3 of the pipe-split row) — a naive
# substring grep for "02-02" also hits it as the Blocked-by CELL of story 02-03's
# row, which reads back as a multi-line "match" instead of one row.
row_for_id() { # row_for_id ID <FILE   — the one row whose ID column equals ID
  awk -F'|' -v want="$2" '
    { id=$3; gsub(/^[ \t]+|[ \t]+$/,"",id); if (id==want) { print; exit } }
  ' "$1"
}
ROW_0202=$(row_for_id "$SI_DEMO" "02-02")
BL_0202=$(printf '%s' "$ROW_0202" | awk -F'|' '{gsub(/^[ \t]+|[ \t]+$/,"",$8); print $8}')
assert_eq "STORIES_INDEX: 02-02 Blocked-by is unquoted 02-01" "02-01" "$BL_0202"

ROW_0103=$(row_for_id "$SI_DEMO" "01-03")
assert_contains "STORIES_INDEX: title with | and \" — pipe escaped" "$ROW_0103" 'Fix "login" bug \| urgent case'

echo
echo "=== EPICS_INDEX rollup ==="
# Feature column reads "NN · Name" — match the epic NUMBER token, not a raw
# substring grep (which could also hit "01" inside some other cell).
FEAT_01=$(awk -F'|' '{f=$2; gsub(/^[ \t]+|[ \t]+$/,"",f); sub(/ .*/,"",f); if (f=="01") { print; exit }}' "$FI")
# NOTE: with 01-03 (epic 01) left in-progress, references/data-model.md's rollup rule
# ("MERGED when every non-skip story is done AND delivery: merged") correctly computes
# IN PROGRESS for epic 01, not MERGED — a story still in flight cannot roll up to a
# finished state. This checks the documented-correct value; see tests/README.md and the
# smoke-test report for the fixture/assertion-brief discrepancy this surfaces.
assert_contains "EPICS_INDEX: epic 01 rollup is IN PROGRESS (01-03 still in-progress)" "$FEAT_01" "IN PROGRESS"

echo
echo "=== ck-view next ==="
NEXT_OUT=$(ck-view next tasks/2026-01-01_demo 2>&1); NEXT_RC=$?
assert_exit "ck-view next: exits 0" 0 "$NEXT_RC"
assert_contains "ck-view next: recommends 02-02 (blocker 02-01 is done)" "$NEXT_OUT" "02-02"
NEXT_RECOMMENDED=$(printf '%s\n' "$NEXT_OUT" | grep -m1 '^\*\*Recommended:\*\*' || true)
assert_not_contains "ck-view next: does not recommend 02-03 (blocker 02-02 not done)" "$NEXT_RECOMMENDED" "02-03"

echo
echo "=== ck-view status / progress / state ==="
STATUS_OUT=$(ck-view status tasks/2026-01-01_demo 2>&1); STATUS_RC=$?
assert_exit "ck-view status: exits 0" 0 "$STATUS_RC"
assert_contains "ck-view status: shows Epic 01 and Epic 02" "$STATUS_OUT" "Epic 01"

PROGRESS_OUT=$(ck-view progress tasks/2026-01-01_demo 2>&1); PROGRESS_RC=$?
assert_exit "ck-view progress: exits 0" 0 "$PROGRESS_RC"
assert_contains "ck-view progress: renders By Epic table" "$PROGRESS_OUT" "By Epic"

STATE_OUT=$(ck-view state 2>&1); STATE_RC=$?
assert_exit "ck-view state: exits 0" 0 "$STATE_RC"
assert_contains "ck-view state: prints project-state probe" "$STATE_OUT" "ck-code: project state"

echo
echo "=== ck-view waves --epic 02 ==="
WAVES_OUT=$(ck-view waves --epic 02 2>&1); WAVES_RC=$?
assert_exit "ck-view waves: exits 0" 0 "$WAVES_RC"
assert_contains "ck-view waves: reports UNSCHEDULABLE" "$WAVES_OUT" "UNSCHEDULABLE"
assert_contains "ck-view waves: 02-04 waiting on 01-03" "$WAVES_OUT" "02-04"
UNSCHED_LINE=$(printf '%s\n' "$WAVES_OUT" | grep '02-04' | grep 'waiting on' || true)
assert_contains "ck-view waves: 02-04's waiting-on names 01-03" "$UNSCHED_LINE" "01-03"
assert_not_contains "ck-view waves: never schedules 02-05 (skip)" "$WAVES_OUT" "02-05"
assert_contains "ck-view waves: 02-06 (bug) is scheduled" "$WAVES_OUT" "02-06"

wave_of() { # wave_of ID <<< "$WAVES_OUT"  — prints the wave number a scheduled id
            # landed in, or nothing if it never appears before UNSCHEDULABLE.
  awk -v id="$1" '
    /^  Wave [0-9]+/ {
      line=$0; sub(/^  Wave /,"",line); split(line,parts," "); w=parts[1]
    }
    /UNSCHEDULABLE/ { exit }
    index($0, id) { print w; exit }
  '
}
W_0202=$(printf '%s\n' "$WAVES_OUT" | wave_of "02-02")
W_0207=$(printf '%s\n' "$WAVES_OUT" | wave_of "02-07")
W_0206=$(printf '%s\n' "$WAVES_OUT" | wave_of "02-06")
if [ -n "$W_0202" ] && [ -n "$W_0207" ]; then
  if [ "$W_0202" != "$W_0207" ]; then
    log_ok "ck-view waves: 02-02 and 02-07 (shared file) land in different waves"
  else
    log_fail "ck-view waves: 02-02 and 02-07 (shared file) land in different waves" "both scheduled in wave $W_0202"
  fi
else
  log_fail "ck-view waves: 02-02 and 02-07 (shared file) land in different waves" "one or both not found scheduled (02-02=$W_0202 02-07=$W_0207)"
fi
assert_true "ck-view waves: 02-06 (bug) scheduled in a real wave" "$([ -n "$W_0206" ]; echo $?)"

echo
echo "=== ck-doctor (clean fixture) ==="
DOCTOR_CLEAN_OUT=$(ck-doctor 2>&1); DOCTOR_CLEAN_RC=$?
assert_exit "ck-doctor: exits 0 on the clean fixture" 0 "$DOCTOR_CLEAN_RC"

DOCTOR_PLAN_CLEAN_OUT=$(ck-doctor tasks/2026-01-01_demo 2>&1); DOCTOR_PLAN_CLEAN_RC=$?
assert_exit "ck-doctor tasks/2026-01-01_demo: exits 0 on the clean fixture" 0 "$DOCTOR_PLAN_CLEAN_RC"

echo
echo "=== ck-doctor worktree include ==="
assert_contains "ck-doctor worktree: OK with no gitignored .env" "$DOCTOR_CLEAN_OUT" "no gitignored .env to copy"
printf '.env\n' > .gitignore; printf 'SECRET=1\n' > .env; printf 'SECRET=\n' > .env.example
WT_WARN_OUT=$(ck-doctor 2>&1); WT_WARN_RC=$?
assert_contains "ck-doctor worktree: WARNs on a gitignored .env with no .worktreeinclude" "$WT_WARN_OUT" "gitignored .env not in .worktreeinclude"
assert_exit "ck-doctor worktree: a WARN still exits 0" 0 "$WT_WARN_RC"
printf '.env\n' > .worktreeinclude
WT_OK_OUT=$(ck-doctor 2>&1)
assert_contains "ck-doctor worktree: OK once .worktreeinclude exists" "$WT_OK_OUT" ".worktreeinclude present"
rm -f .gitignore .env .env.example .worktreeinclude

echo
echo "=== ck-story get/set round-trip ==="
STORY_0203="tasks/2026-01-01_demo/epics/02_payments/stories/03_invoice.md"
GET_BEFORE=$(ck-story get "$STORY_0203" size 2>&1)
assert_contains "ck-story get: 02-03 starts at size S" "$GET_BEFORE" "size: S"
SET_M_OUT=$(ck-story set "$STORY_0203" size=M 2>&1); SET_M_RC=$?
assert_exit "ck-story set: 02-03 size=M exits 0" 0 "$SET_M_RC"
GET_M=$(ck-story get "$STORY_0203" size 2>&1)
assert_contains "ck-story set: 02-03 size is now M" "$GET_M" "size: M"
SET_BACK_OUT=$(ck-story set "$STORY_0203" size=S 2>&1); SET_BACK_RC=$?
assert_exit "ck-story set: 02-03 size=S (revert) exits 0" 0 "$SET_BACK_RC"
GET_BACK=$(ck-story get "$STORY_0203" size 2>&1)
assert_contains "ck-story set: 02-03 size reverted to S" "$GET_BACK" "size: S"

echo
echo "=== ck-bootstrap check ==="
BOOTSTRAP_OUT=$(ck-bootstrap check 2>&1); BOOTSTRAP_RC=$?
assert_exit "ck-bootstrap check: exits 0 (read-only report)" 0 "$BOOTSTRAP_RC"

echo
echo "=== hook scripts (statusline / session-start / subagent-statusline / prompt-router) ==="
STATUSLINE_JSON=$(printf '{"workspace":{"current_dir":"%s"}}' "$FIXTURE")
STATUSLINE_OUT=$(printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/statusline.sh" 2>&1); STATUSLINE_RC=$?
assert_exit "statusline.sh: exits 0" 0 "$STATUSLINE_RC"
assert_contains "statusline.sh: renders the active story's title with \" and | intact" "$STATUSLINE_OUT" 'login" bug |'
assert_contains "statusline.sh: counts acceptance criteria only (2, not 3)" "$STATUSLINE_OUT" "0/2"

SESSION_OUT=$(printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/session-start.sh" 2>&1); SESSION_RC=$?
assert_exit "session-start.sh: exits 0" 0 "$SESSION_RC"
assert_contains "session-start.sh: emits a SessionStart hook JSON line" "$SESSION_OUT" '"hookSpecificOutput"'
assert_contains "session-start.sh: summarises the plan" "$SESSION_OUT" "TODO"
if [ "$HAVE_JQ" -eq 1 ]; then
  assert_true "session-start.sh: output is valid JSON" "$(printf '%s' "$SESSION_OUT" | jq -e . >/dev/null 2>&1; echo $?)"
fi

echo
echo "=== views out of git, regenerated at session start ==="
assert_eq "git status: clean after ck-index, ck-view and session-start" "" "$(git status --porcelain -- tasks)"
rm -f tasks/2026-01-01_demo/STORIES_INDEX.md tasks/EPICS_INDEX.md
printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/session-start.sh" >/dev/null 2>&1
assert_true "session-start.sh: recreates a deleted STORIES_INDEX.md" "$([ -f tasks/2026-01-01_demo/STORIES_INDEX.md ]; echo $?)"
assert_true "session-start.sh: recreates a deleted EPICS_INDEX.md" "$([ -f tasks/EPICS_INDEX.md ]; echo $?)"
sleep 1
S_0203="tasks/2026-01-01_demo/epics/02_payments/stories/03_invoice.md"
sed 's/^title: Invoice generation$/title: Invoice PDFs/' "$S_0203" > "$S_0203.tmp" && mv "$S_0203.tmp" "$S_0203"
STALE_OUT=$(ck-view status tasks/2026-01-01_demo 2>&1)
assert_contains "ck-view: regenerates a view older than its frontmatter" "$STALE_OUT" "Invoice PDFs"
git checkout -q -- "$S_0203"
ck-index >/dev/null 2>&1

echo
echo "=== session-start: both directions of a layout mismatch ==="
cp tasks/VERSION.md "$FIXTURE/.version.bak"
printf 'layout: v6\n' > tasks/VERSION.md
OLDER_OUT=$(printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/session-start.sh" 2>&1)
assert_contains "session-start.sh: an older layout is sent to migrate" "$OLDER_OUT" "/ck-code:migrate"
printf 'layout: v99\n' > tasks/VERSION.md
NEWER_OUT=$(printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/session-start.sh" 2>&1)
assert_contains "session-start.sh: a newer layout asks for a plugin update" "$NEWER_OUT" "/plugin update"
assert_not_contains "session-start.sh: a newer layout is never sent to migrate" "$NEWER_OUT" "Run /ck-code:migrate"
printf 'layout: v7\nrequires: ck-code >= 99.0.0\n' > tasks/VERSION.md
REQ_OUT=$(printf '%s' "$STATUSLINE_JSON" | "$PLUGIN_ROOT/scripts/session-start.sh" 2>&1)
assert_contains "session-start.sh: an unmet requires: asks for a plugin update" "$REQ_OUT" "requires ck-code >= 99.0.0"
REQ_DOC=$(ck-doctor 2>&1)
assert_contains "ck-doctor: an unmet requires: is an ERROR" "$REQ_DOC" "requires ck-code >= 99.0.0"
cp "$FIXTURE/.version.bak" tasks/VERSION.md; rm -f "$FIXTURE/.version.bak"
assert_eq "session-start.sh: never rewrites the stamp" "" "$(git status --porcelain -- tasks/VERSION.md)"

if [ "$HAVE_JQ" -eq 1 ]; then
  SUBAGENT_JSON=$(cat <<EOF
{"tasks":[{"id":"t1","name":"story-02-03","type":"agent","status":"running","description":"Implement invoice generation","label":"story-02-03","startTime":"","tokenCount":12345,"cwd":"$FIXTURE"}]}
EOF
)
  SUBAGENT_OUT=$(printf '%s' "$SUBAGENT_JSON" | "$PLUGIN_ROOT/scripts/subagent-statusline.sh" 2>&1); SUBAGENT_RC=$?
  assert_exit "subagent-statusline.sh: exits 0" 0 "$SUBAGENT_RC"
  assert_contains "subagent-statusline.sh: renders a row for the dispatched story" "$SUBAGENT_OUT" "02-03"
else
  log_skip "subagent-statusline.sh: jq not on PATH — script no-ops by design, skipping content assertion"
fi

# prompt-router.sh: routes a free-text prompt, stays silent on a slash command, a short
# reply, and outside an adopted project (references/prompt-routing.md is the payload).
ROUTER="$PLUGIN_ROOT/scripts/prompt-router.sh"
ROUTER_OUT=$(printf '{"cwd":"%s","prompt":"fix the \\"login\\" bug, it crashes on submit"}' "$FIXTURE" | "$ROUTER" 2>&1); ROUTER_RC=$?
assert_exit "prompt-router.sh: exits 0" 0 "$ROUTER_RC"
assert_contains "prompt-router.sh: emits a UserPromptSubmit hook JSON line" "$ROUTER_OUT" '"hookEventName":"UserPromptSubmit"'
assert_contains "prompt-router.sh: injects the routing table" "$ROUTER_OUT" 'ck-code router'
if [ "$HAVE_JQ" -eq 1 ]; then
  assert_true "prompt-router.sh: output is valid JSON" "$(printf '%s' "$ROUTER_OUT" | jq -e . >/dev/null 2>&1; echo $?)"
fi
ROUTER_SLASH=$(printf '{"prompt":"/ck-code:fix"}' | "$ROUTER" 2>&1)
assert_eq "prompt-router.sh: silent on a slash command" "" "$ROUTER_SLASH"
ROUTER_SHORT=$(printf '{"prompt":"yes"}' | "$ROUTER" 2>&1)
assert_eq "prompt-router.sh: silent on a short reply" "" "$ROUTER_SHORT"
ROUTER_ELSEWHERE=$(cd "$(mktemp -d)" && printf '{"prompt":"fix the login bug please"}' | "$ROUTER" 2>&1)
assert_eq "prompt-router.sh: silent outside an adopted project" "" "$ROUTER_ELSEWHERE"

echo
echo "=== one Ready rule: a skipped blocker releases its dependant ==="
assert_contains "ck-view next: 02-08 (blocked only by skipped 02-05) is ready" "$NEXT_OUT" "02-08"
W_0208=$(printf '%s\n' "$WAVES_OUT" | wave_of "02-08")
assert_true "ck-view waves: 02-08 is scheduled, not UNSCHEDULABLE" "$([ -n "$W_0208" ]; echo $?)"
assert_not_contains "ck-doctor: no dependency complaint about 02-08" "$DOCTOR_CLEAN_OUT" "02-08"

echo
echo "=== shared library: atomic, loud frontmatter writes ==="
# shellcheck source=scripts/lib/ck-common.sh
. "$PLUGIN_ROOT/scripts/lib/ck-common.sh"
LIBDIR="$(mktemp -d)"
printf -- '---\r\nid: 09-01\r\nstatus: todo\r\n---\r\n\r\n# Body\r\n' > "$LIBDIR/crlf.md"
ck_fm_set "$LIBDIR/crlf.md" status done
assert_eq "ck_fm_set: CRLF story value written" "done" "$(ck_fm "$LIBDIR/crlf.md" status)"
assert_eq "ck_fm_set: CRLF line endings preserved" "6" "$(grep -c $'\r$' "$LIBDIR/crlf.md")"
printf '# no frontmatter\n' > "$LIBDIR/nofence.md"
ck_fm_set "$LIBDIR/nofence.md" status done 2>/dev/null; NOFENCE_RC=$?
assert_exit "ck_fm_set: refuses a file with no fence" 1 "$NOFENCE_RC"
printf -- '---\nid: 09-02\nstatus: todo\n' > "$LIBDIR/open.md"
ck_fm_set "$LIBDIR/open.md" status done 2>/dev/null; OPEN_RC=$?
assert_exit "ck_fm_set: refuses an unterminated fence" 1 "$OPEN_RC"
assert_eq "ck_fm_set: unterminated file left untouched" "todo" "$(awk -F': ' '/^status/{print $2}' "$LIBDIR/open.md")"
chmod 640 "$LIBDIR/crlf.md"; ck_fm_set "$LIBDIR/crlf.md" pr 12
assert_eq "ck_fm_set: file mode survives the rename" "640" "$(ls -l "$LIBDIR/crlf.md" | awk '{m=$1; o=0; for(i=2;i<=10;i++){c=substr(m,i,1); if(c!="-") o+= (i%3==2?4:(i%3==0?2:1)) * (i<=4?100:(i<=7?10:1))} print o}')"
assert_eq "ck_flow_list: unquotes and splits" "02-01|02-03" "$(ck_flow_list '["02-01", 02-03]' | paste -sd'|' -)"
rm -rf "$LIBDIR"

echo
echo "=== ck-story: loud failure, files merge ==="
NOFENCE_STORY="tasks/2026-01-01_demo/epics/02_payments/stories/99_nofence.md"
printf '# not a story\n' > "$NOFENCE_STORY"
NF_OUT=$(ck-story set "$NOFENCE_STORY" status=done --no-sync 2>&1); NF_RC=$?
assert_exit "ck-story set: exits 1 when the write failed" 1 "$NF_RC"
assert_contains "ck-story set: says why" "$NF_OUT" "no frontmatter fence"
rm -f "$NOFENCE_STORY"
FILES_OUT=$(ck-story files "$STORY_0203" src/payments/invoice.ts src/payments/pdf.ts ./src/payments/pdf.ts 2>&1)
assert_eq "ck-story files: merged, sorted, de-duplicated" "[src/payments/invoice.ts, src/payments/pdf.ts]" "$(ck-story get "$STORY_0203" files | sed 's/^files: //')"
git checkout -q -- "$STORY_0203"
SET_FILES_OUT=$(ck-story set "$STORY_0203" files=x 2>&1)
assert_contains "ck-story set: refuses files= and points at ck-story files" "$SET_FILES_OUT" "ck-story files"

echo
echo "=== ck-project against a fake gh ==="
if [ "$HAVE_JQ" -eq 1 ]; then
  FAKE_BIN="$PLUGIN_ROOT/tests/fake-gh"
  export CK_PROJECT_PACE=0
  # fresh_copy — a throwaway clone of the clean fixture plus an empty canned-gh dir.
  fresh_copy() {
    PJ="$(mktemp -d)"; export FAKE_GH="$PJ/.gh"; mkdir -p "$FAKE_GH"
    git -C "$FIXTURE" stash -q -u >/dev/null 2>&1 || true
    cp -R "$FIXTURE/." "$PJ/"
    git -C "$FIXTURE" stash pop -q >/dev/null 2>&1 || true
    ( cd "$PJ" && git checkout -q main && git clean -qfd -e .gh )
    printf '{"nameWithOwner":"fake/repo","defaultBranchRef":{"name":"main"}}\n' > "$FAKE_GH/repo-view.json"
    : > "$FAKE_GH/calls.log"
  }
  S0201="tasks/2026-01-01_demo/epics/02_payments/stories/01_charge.md"

  # A: no board, nothing to ask GitHub → no gh call at all.
  fresh_copy
  A_OUT=$(cd "$PJ" && PATH="$FAKE_BIN:$PATH" ck-project sync 2>&1); A_RC=$?
  assert_exit "sync, no board, no open PR: exits 0" 0 "$A_RC"
  assert_contains "sync, no board: says cards were skipped" "$A_OUT" "no board configured"
  assert_eq "sync, no board, no open PR: made no gh call" "" "$(cat "$FAKE_GH/calls.log")"
  rm -rf "$PJ"

  # B: no board, a recorded PR merged into the trunk → delivery: merged.
  fresh_copy
  ( cd "$PJ" && ck-story set "$S0201" pr=5 --no-sync >/dev/null )
  printf '[{"number":5,"state":"MERGED","baseRefName":"main"}]\n' > "$FAKE_GH/pr-list.json"
  B_OUT=$(cd "$PJ" && PATH="$FAKE_BIN:$PATH" ck-project sync 2>&1); B_RC=$?
  assert_exit "sync, no board, merged PR: exits 0" 0 "$B_RC"
  assert_eq "sync, no board: delivery reaches merged" "merged" "$(ck_fm "$PJ/$S0201" delivery)"
  assert_contains "sync, no board: reports the delivery change" "$B_OUT" "1 delivery updated"
  B_ROW=$(awk -F'|' '{id=$3; gsub(/ /,"",id); if (id=="02-01") print}' "$PJ/tasks/2026-01-01_demo/STORIES_INDEX.md")
  assert_contains "sync, no board: the view shows MERGED" "$B_ROW" "MERGED"
  rm -rf "$PJ"

  # C: a board — cards placed from status and delivery; a skipped blocker lands in Todo.
  fresh_copy
  cat > "$PJ/tasks/SETTINGS.md" <<'EOF'
---
github_issues: true
github_repo: fake/repo
github_project_owner: fake
github_project_number: 1
github_project_id: PVT_1
board_field: Status
board_todo: Todo
board_in_progress: In Progress
board_blocked: Blocked
board_done: Done
---
EOF
  cat > "$FAKE_GH/field-list.json" <<'EOF'
{"fields":[{"id":"F1","name":"Status","type":"ProjectV2SingleSelectField","options":[
 {"id":"o_todo","name":"Todo"},{"id":"o_ip","name":"In Progress"},
 {"id":"o_blk","name":"Blocked"},{"id":"o_done","name":"Done"}]}]}
EOF
  printf '{"items":[{"id":"I58","status":"Blocked","repository":"https://github.com/fake/repo","content":{"number":58}}]}\n' > "$FAKE_GH/item-list.json"
  C_DRY=$(cd "$PJ" && PATH="$FAKE_BIN:$PATH" ck-project sync --dry-run 2>&1)
  assert_contains "sync, board, dry run: moves 02-08 to Todo" "$C_DRY" "#58  Blocked → Todo"
  assert_not_contains "sync, board, dry run: edits nothing" "$(cat "$FAKE_GH/calls.log")" "item-edit"
  C_OUT=$(cd "$PJ" && PATH="$FAKE_BIN:$PATH" ck-project sync 2>&1); C_RC=$?
  assert_exit "sync, board: exits 0" 0 "$C_RC"
  assert_contains "sync, board: the move reached gh" "$(cat "$FAKE_GH/calls.log")" "project item-edit --id I58"
  rm -rf "$PJ"

  # D: issues — a delivered story's open issue is closed.
  fresh_copy
  ( cd "$PJ" && ck-story set "$S0201" issue=11 delivery=direct --no-sync >/dev/null )
  printf -- '---\ngithub_issues: true\ngithub_repo: fake/repo\n---\n' > "$PJ/tasks/SETTINGS.md"
  printf '[{"number":11,"state":"OPEN"}]\n' > "$FAKE_GH/issue-list.json"
  D_OUT=$(cd "$PJ" && PATH="$FAKE_BIN:$PATH" ck-project issues 2>&1); D_RC=$?
  assert_exit "issues: exits 0" 0 "$D_RC"
  assert_contains "issues: closes the delivered story's issue" "$(cat "$FAKE_GH/calls.log")" "issue close 11"
  rm -rf "$PJ"

  # E: closes — the footer comes from frontmatter alone.
  E_OUT=$(ck-project closes "tasks/2026-01-01_demo/epics/02_payments/stories/08_audit.md" 2>&1)
  assert_eq "closes: a story's footer" "Closes #58" "$E_OUT"

  # F: landed — a finished story whose code is on the trunk becomes direct.
  fresh_copy
  ( cd "$PJ" && mkdir -p src/payments && echo x > src/payments/charge.ts \
      && git add -A && git commit -qm "feat: charge" )
  F_OUT=$(cd "$PJ" && ck-project landed 2>&1)
  assert_contains "landed: 02-01 is marked direct" "$F_OUT" "02-01  (none) → direct"
  assert_eq "landed: frontmatter says direct" "direct" "$(ck_fm "$PJ/$S0201" delivery)"
  rm -rf "$PJ"
  unset FAKE_GH
else
  log_skip "ck-project fake-gh tests: jq not on PATH"
fi

echo
echo "=== ck-migrate v7: a v6 project converts in one commit ==="
V6="$(mktemp -d)"
(
  cd "$V6" || exit 1
  mkdir -p tasks/2026-03-03_feature-billing/epics/01_invoices/stories tasks/2026-03-03_feature-billing/epics/02_refunds/stories
  printf 'ck-code: 6.17.1\nlayout: v6\n' > tasks/VERSION.md
  printf '# Feature Overview: Billing\n\n## Vision\n\nBill people.\n' > tasks/2026-03-03_feature-billing/FEATURE_OVERVIEW.md
  for e in 01_invoices 02_refunds; do
    n=${e%%_*}
    printf -- '---\nepic: %s\nslug: %s\ntitle: T\ndescription: D\nissue:\npr: 42\ndelivery: pr\nintegration: feature\n---\n\n# Epic\n\n## Dependencies\n\n- **Depends on:** None\n\n## Acceptance Criteria\n\n- [ ] ok\n' "$n" "${e#*_}" > "tasks/2026-03-03_feature-billing/epics/$e/EPIC.md"
    printf -- '---\nid: %s-01\ntitle: S\nepic: %s\nstatus: todo\nsize: S\nblocked_by: []\nfiles: []\nissue:\npr:\ndelivery:\nprior_status:\n---\n\n# S\n' "$n" "$n" > "tasks/2026-03-03_feature-billing/epics/$e/stories/01_s.md"
  done
  printf '# Stories Index\n' > tasks/2026-03-03_feature-billing/STORIES_INDEX.md
  printf '# Feature Index\n' > tasks/FEATURE_INDEX.md
  mkdir -p docs/specs/2026-03-01_billing docs/architecture/design-system
  printf '# Spec\n' > docs/specs/2026-03-01_billing/pre-spec.md
  printf '{\n  "slug": "billing",\n  "status": "draft",\n  "stage": "spec",\n  "tags": []\n}\n' > docs/specs/2026-03-01_billing/.metadata.json
  printf -- '---\nproject_id: p1\nproject_name: DS\nproject_updated_at: 2026-03-01T00:00:00Z\nsynced_at: 2026-03-01\ntokens_path: pending\n---\n\n# Design System\n' > docs/architecture/design-system/index.md
  printf '{\n  "projectId": "p1",\n  "cards": []\n}\n' > docs/architecture/design-system/manifest.json
  git init -q . && git symbolic-ref HEAD refs/heads/main
  git config user.email smoke@ck-code.test && git config user.name smoke
  git add -A && git commit -qm "v6 project"
  git branch -q feat/2026-03-03_feature-billing
)
MIG_OUT=$(cd "$V6" && ck-migrate v7 --commit 2>&1); MIG_RC=$?
assert_exit "ck-migrate: exits 0" 0 "$MIG_RC"
OV="$V6/tasks/2026-03-03_feature-billing/OVERVIEW.md"
assert_true "ck-migrate: FEATURE_OVERVIEW.md became OVERVIEW.md" "$([ -f "$OV" ] && [ ! -f "$V6/tasks/2026-03-03_feature-billing/FEATURE_OVERVIEW.md" ]; echo $?)"
assert_eq "ck-migrate: feature level became plan" "plan" "$(ck_fm "$OV" integration)"
assert_eq "ck-migrate: the existing feat/ branch is kept" "feat/2026-03-03_feature-billing" "$(ck_fm "$OV" branch)"
assert_eq "ck-migrate: the plan PR moved to the record" "42" "$(ck_fm "$OV" pr)"
assert_eq "ck-migrate: the title lost the template prefix" "Billing" "$(ck_fm "$OV" title)"
assert_eq "ck-migrate: slug drops the date and feature- prefix" "billing" "$(ck_fm "$OV" slug)"
EP1="$V6/tasks/2026-03-03_feature-billing/epics/01_invoices/EPIC.md"
assert_eq "ck-migrate: EPIC.md loses integration:" "" "$(grep '^integration:' "$EP1")"
assert_eq "ck-migrate: EPIC.md loses the copied plan PR" "" "$(ck_fm "$EP1" pr)"
assert_contains "ck-migrate: EPIC.md keeps its Dependencies prose" "$(cat "$EP1")" "## Dependencies"
assert_eq "ck-migrate: views untracked" "" "$(git -C "$V6" ls-files 'tasks/*INDEX.md')"
assert_true "ck-migrate: EPICS_INDEX.md regenerated" "$([ -f "$V6/tasks/EPICS_INDEX.md" ]; echo $?)"
assert_true "ck-migrate: pre-spec.md became spec.md" "$([ -f "$V6/docs/specs/2026-03-01_billing/spec.md" ]; echo $?)"
assert_not_contains "ck-migrate: spec metadata drops stage" "$(cat "$V6/docs/specs/2026-03-01_billing/.metadata.json")" '"stage"'
assert_true "ck-migrate: spec metadata is still valid JSON" "$(python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$V6/docs/specs/2026-03-01_billing/.metadata.json"; echo $?)"
assert_contains "ck-migrate: tokensPath moved into manifest.json" "$(cat "$V6/docs/architecture/design-system/manifest.json")" '"tokensPath": "pending"'
assert_eq "ck-migrate: index.md frontmatter removed" "# Design System" "$(head -1 "$V6/docs/architecture/design-system/index.md")"
assert_eq "ck-migrate: stamp is v7" "v7" "$(cd "$V6" && ck_stamp layout)"
assert_eq "ck-migrate: tree clean after the commit" "" "$(git -C "$V6" status --porcelain)"
assert_contains "ck-migrate: a second run is a no-op" "$(cd "$V6" && ck-migrate v7 2>&1)" "already v7"
printf 'layout: v9\n' > "$V6/tasks/VERSION.md"
NEWER_MIG=$(cd "$V6" && ck-migrate v7 2>&1); NEWER_MIG_RC=$?
assert_exit "ck-migrate: refuses a newer layout" 1 "$NEWER_MIG_RC"
assert_contains "ck-migrate: says to update the plugin" "$NEWER_MIG" "update the plugin"
rm -rf "$V6"

echo
echo "=== team refresh contract: SOURCES stamp vs the tech stack ==="
TEAM="$(mktemp -d)"
(
  cd "$TEAM" || exit 1
  mkdir -p docs/architecture .claude/skills/guide-react .claude/skills/expert-qa .claude/skills/guide-conventions tasks
  printf '# Tech stack\n\n- React 18\n' > docs/architecture/tech-stack.md
  printf '# Folders\n' > docs/architecture/folder-structure.md
)
DIG=$(cd "$TEAM" && ck_team_digest)
assert_eq "ck_team_digest: 12 hex characters" "12" "${#DIG}"
printf -- '---\nname: guide-react\ndescription: Use when writing React.\n---\n<!-- ck-code:team GENERATED — x -->\n<!-- ck-code:team SOURCES %s -->\n' "$DIG" > "$TEAM/.claude/skills/guide-react/SKILL.md"
printf -- '---\nname: expert-qa\ndescription: Use when testing.\n---\n<!-- ck-code:team GENERATED — x -->\n' > "$TEAM/.claude/skills/expert-qa/SKILL.md"
printf -- '---\nname: guide-conventions\ndescription: Use always.\n---\n# House rules\n' > "$TEAM/.claude/skills/guide-conventions/SKILL.md"
assert_eq "ck_team_stale: only the unstamped owned skill" ".claude/skills/expert-qa/SKILL.md" "$(cd "$TEAM" && ck_team_stale)"
printf -- '- React 19\n' >> "$TEAM/docs/architecture/tech-stack.md"
assert_eq "ck_team_stale: a tech-stack change stales the stamped one too" "2" "$(cd "$TEAM" && ck_team_stale | grep -c .)"
TEAM_DOC=$(cd "$TEAM" && ck-doctor 2>&1)
assert_contains "ck-doctor: reports stale team skills" "$TEAM_DOC" "written against an older tech stack"
assert_not_contains "ck-doctor: a protected skill is never stale" "$TEAM_DOC" "guide-conventions/SKILL.md"
rm -rf "$TEAM"

echo
echo "=== breaking a second plan (tasks/2026-02-02_other, story missing id) ==="
add_broken_plan

DOCTOR_ALL_OUT=$(ck-doctor 2>&1); DOCTOR_ALL_RC=$?
assert_exit "ck-doctor (no arg): reports the broken plan (exit 1)" 1 "$DOCTOR_ALL_RC"
assert_contains "ck-doctor (no arg): mentions the broken plan" "$DOCTOR_ALL_OUT" "2026-02-02_other"

DOCTOR_SCOPED_OUT=$(ck-doctor tasks/2026-01-01_demo 2>&1); DOCTOR_SCOPED_RC=$?
assert_exit "ck-doctor tasks/2026-01-01_demo: still exits 0 (scoped to the clean plan)" 0 "$DOCTOR_SCOPED_RC"
assert_not_contains "ck-doctor tasks/2026-01-01_demo: does not mention the other plan" "$DOCTOR_SCOPED_OUT" "2026-02-02_other"

echo
echo "=== ck-story WARN passthrough on the broken plan ==="
BROKEN_STORY="tasks/2026-02-02_other/epics/03_other/stories/01_broken.md"
STORY_WARN_OUT=$(ck-story set "$BROKEN_STORY" size=M 2>&1); STORY_WARN_RC=$?
# references/stories-index.md: every caller of ck-index relays its WARN lines.
assert_contains "ck-story set: relays ck-index's WARN for the broken story" "$STORY_WARN_OUT" "ck-index: WARN"

echo
echo "=== shellcheck ==="
if command -v shellcheck >/dev/null 2>&1; then
  SC_OUT=$(cd "$PLUGIN_ROOT" && shellcheck -x -S warning scripts/*.sh scripts/lib/*.sh bin/* tests/fake-gh/gh 2>&1); SC_RC=$?
  if [ "$SC_RC" -eq 0 ]; then
    log_ok "shellcheck -S warning: scripts/*.sh bin/* clean"
  else
    log_fail "shellcheck -S warning: scripts/*.sh bin/* clean" "$SC_OUT"
  fi
else
  log_skip "shellcheck not on PATH — skipping lint pass"
fi

echo
echo "smoke: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
exit 0
