# shellcheck shell=bash
# ck-common.sh — the one implementation of every rule more than one ck-code script needs.
#
# Sourced, never executed. Defines functions and constants only; sourcing it changes no
# state, prints nothing and never exits. Every script resolves it relative to itself:
#
#   CK_HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
#   . "$CK_HERE/lib/ck-common.sh"
#
# Before this file existed the frontmatter reader had 13 copies, the writer 3 that
# disagreed, and the Ready rule 3 that gave different answers for a skipped blocker.
# A rule that lives here is the rule; a script that re-implements one is a bug.
#
# Portable to bash 3.2: no associative arrays, no mapfile, no ${v,,}.

CK_STAMP_MARK="GENERATED by ck-code"

# The version of the committed .claude/ck-code-required.sh guard. ck-bootstrap writes it;
# session-start and ck-doctor compare the installed guard against it.
# shellcheck disable=SC2034  # read by the scripts that source this file
CK_GUARD_VERSION=1

# The overview file that marks a directory under tasks/ as a plan. v7 writes OVERVIEW.md;
# the two v6 names are read so a project mid-migration is still visible to the converter.
CK_OVERVIEW_NAMES="OVERVIEW.md PROJECT_OVERVIEW.md FEATURE_OVERVIEW.md"

# ck_root — cd to the repository root holding tasks/, so every relative path resolves the
# same way from any subdirectory (a dispatched subagent often runs from one). Returns 1
# when no tasks/ is reachable; the caller decides whether that is an error.
ck_root() {
  [ -d tasks ] && return 0
  local r
  r="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  [ -n "$r" ] && [ -d "$r/tasks" ] || return 1
  cd "$r" || return 1
}

# ck_fm FILE KEY — print one frontmatter scalar, surrounding quotes stripped. Reads only
# the first --- fence, tolerates CRLF, prints nothing for an absent key or file.
ck_fm() {
  [ -f "$1" ] || return 0
  awk -v key="$2" '
    function unquote(s) {
      if (s ~ /^".*"$/ || s ~ /^\047.*\047$/) s = substr(s, 2, length(s)-2)
      return s
    }
    { sub(/\r$/,"") }
    FNR==1 && $0!="---" { exit }
    FNR==1 { next }
    $0=="---" { exit }
    { i=index($0,":"); if (i>0) { k=substr($0,1,i-1); v=substr($0,i+1)
        gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v)
        if (k==key) { print unquote(v); exit } } }
  ' "$1"
}

# ck_fm_dump FILE — print the frontmatter block without its fences.
ck_fm_dump() {
  [ -f "$1" ] || return 0
  awk '{ sub(/\r$/,"") } FNR==1 && $0!="---" { exit } FNR==1 { next } $0=="---" { exit } { print }' "$1"
}

# ck_fm_set FILE KEY VALUE — set one frontmatter scalar, appending the key before the
# closing fence when it is absent. An empty VALUE writes `key:`.
#
# Atomic: the new content is written to a temp file beside FILE (a copy of FILE first, so
# it carries FILE's mode) and renamed over it, so a reader — the status line re-reads
# every few seconds — never sees a half-written file. CRLF files stay CRLF.
#
# Fails loudly, returning 1 with a message on stderr, when FILE has no opening fence or
# no closing one. It never reports success for a write it did not make.
ck_fm_set() {
  local f="$1" k="$2" v="$3" tmp rc
  [ -f "$f" ] || { echo "ck: no such file: $f" >&2; return 1; }
  if [ "$(head -1 "$f" | tr -d '\r')" != "---" ]; then
    echo "ck: $f has no frontmatter fence — \`$k\` not written" >&2
    return 1
  fi
  tmp="$(mktemp "$f.ck.XXXXXX")" || { echo "ck: cannot create a temp file beside $f" >&2; return 1; }
  cp -p "$f" "$tmp" 2>/dev/null
  awk -v key="$k" -v val="$v" '
    function line(s) { return s (crlf ? "\r" : "") }
    { cr = sub(/\r$/,"") }
    FNR==1 { crlf = cr; inb=1; print line($0); next }
    inb && $0=="---" {
      if (!done) print line(val=="" ? key ":" : key ": " val)
      done=1; inb=0; print line($0); next
    }
    inb {
      i=index($0,":")
      if (i>0) { k2=substr($0,1,i-1); gsub(/^[ \t]+|[ \t]+$/,"",k2)
        if (k2==key) { if (!done) print line(val=="" ? key ":" : key ": " val); done=1; next } }
      print line($0); next
    }
    { print line($0) }
    END { exit (inb ? 2 : 0) }
  ' "$f" > "$tmp"
  rc=$?
  if [ "$rc" -ne 0 ]; then
    rm -f "$tmp"
    [ "$rc" -eq 2 ] && echo "ck: $f has an unterminated frontmatter fence — \`$k\` not written" >&2
    return 1
  fi
  mv -f "$tmp" "$f" || { rm -f "$tmp"; echo "ck: could not replace $f" >&2; return 1; }
}

# ck_write_atomic DEST — copy stdin to DEST through a temp file and a rename.
ck_write_atomic() {
  local dest="$1" tmp
  tmp="$(mktemp "$dest.ck.XXXXXX" 2>/dev/null)" || { cat > "$dest"; return; }
  if cat > "$tmp"; then mv -f "$tmp" "$dest"; else rm -f "$tmp"; return 1; fi
}

# ck_plans — every plan directory under tasks/, one per line, sorted.
ck_plans() {
  local n expr=""
  for n in $CK_OVERVIEW_NAMES; do expr="$expr${expr:+ -o} -name $n"; done
  # shellcheck disable=SC2086  # $expr is a find expression built from fixed names
  find tasks -mindepth 2 -maxdepth 2 \( $expr \) 2>/dev/null | sed 's|/[^/]*$||' | sort -u
}

# ck_plan_overview PLAN — the overview file of one plan (empty when it has none).
ck_plan_overview() {
  local n
  for n in $CK_OVERVIEW_NAMES; do
    [ -f "$1/$n" ] && { printf '%s' "$1/$n"; return 0; }
  done
  return 1
}

# ck_epic_dirs [PLAN] — every epic directory, in plan and number order.
ck_epic_dirs() {
  if [ -n "${1:-}" ]; then
    find "$1/epics" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort
  else
    find tasks -mindepth 3 -maxdepth 3 -type d -path 'tasks/*/epics/*' 2>/dev/null | sort
  fi
}

# ck_story_files [PLAN|EPICDIR] — every story file under a plan, an epic, or tasks/.
ck_story_files() {
  local scope="${1:-tasks}"
  if [ -d "$scope/stories" ]; then
    find "$scope/stories" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort
  else
    find "$scope" -type f -path '*/epics/*/stories/*.md' 2>/dev/null | sort
  fi
}

# ck_plan_of STORY|EPICDIR — tasks/<slug> for a path somewhere inside a plan.
ck_plan_of() {
  printf '%s' "$1" | sed 's|/epics/.*||'
}

# ck_flow_list RAW — one element per line from a YAML flow list such as ["02-01", 02-03].
ck_flow_list() {
  printf '%s' "$1" | tr -d "[]'\"" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | grep -v '^$' || true
}

# ck_blocker_met STATUS — the Ready rule's one question: does a blocker in this status
# still hold its dependants back? `done` and `skip` release them. A skipped story is work
# the plan decided not to do, and a dependant waiting on it would wait forever.
ck_blocker_met() {
  case "$1" in done|skip) return 0 ;; esac
  return 1
}

# The same rule for awk programs that hold statuses in their upper-case index form.
# shellcheck disable=SC2034  # read by the scripts that source this file
CK_AWK_MET='function met(s) { return s=="DONE" || s=="SKIP" }'

# ck_json_escape STRING — escape for a JSON double-quoted value; newlines become spaces.
ck_json_escape() {
  printf '%s' "$1" | awk '
    BEGIN { ORS="" }
    { gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); gsub(/\t/,"\\t"); if (NR>1) print " "; print }
  '
}

# ck_view_fresh PLAN — 0 when PLAN/STORIES_INDEX.md exists, carries the generated stamp,
# and no markdown file of the plan is newer than it. The views are not committed, so a
# clone, a checkout or a pull can leave one missing or behind its frontmatter.
ck_view_fresh() {
  local idx="$1/STORIES_INDEX.md"
  [ -f "$idx" ] && grep -q "$CK_STAMP_MARK" "$idx" 2>/dev/null || return 1
  [ -z "$(find "$1" -name '*.md' ! -name STORIES_INDEX.md -newer "$idx" 2>/dev/null | head -1)" ]
}

# ck_views_fresh — every plan view fresh and the cross-plan epic index present and newer
# than every plan view.
ck_views_fresh() {
  local p
  [ -f tasks/EPICS_INDEX.md ] || return 1
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    ck_view_fresh "$p" || return 1
    [ "$p/STORIES_INDEX.md" -nt tasks/EPICS_INDEX.md ] && return 1
  done < <(ck_plans)
  return 0
}

# ck_version_lt A B — 0 when dotted version A sorts before B (7.0.0 < 7.0.10 < 7.1.0).
ck_version_lt() {
  awk -v a="$1" -v b="$2" 'BEGIN {
    na = split(a, x, "."); nb = split(b, y, "."); n = (na > nb) ? na : nb
    for (i = 1; i <= n; i++) { p = x[i] + 0; q = y[i] + 0
      if (p < q) exit 0
      if (p > q) exit 1 }
    exit 1 }'
}

# ck_stamp KEY — one line of tasks/VERSION.md (`layout`, `requires`), value only.
# `requires: ck-code >= 7.0.0` yields `7.0.0`.
ck_stamp() {
  [ -f tasks/VERSION.md ] || return 0
  awk -v k="$1" -F: '$1==k { v=$2; for (i=3;i<=NF;i++) v=v ":" $i
      gsub(/^[ \t]+|[ \t]+$/,"",v); sub(/^ck-code[ \t]*>=[ \t]*/,"",v); print v; exit }' tasks/VERSION.md
}

# ck_plugin_version — the running plugin's version, from its manifest.
ck_plugin_version() {
  local pj
  pj="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd -P)/.claude-plugin/plugin.json"
  [ -f "$pj" ] && awk -F'"' '/"version"[[:space:]]*:/{print $4; exit}' "$pj"
}

# ck_run NAME ARGS… — run a sibling ck-code script. The sibling beside the library wins
# over PATH, so a Workflow subagent with an empty $CLAUDE_PLUGIN_ROOT still finds it.
# Returns 127 when neither exists.
ck_run() {
  local name="$1" dir
  shift
  dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
  if [ -f "$dir/$name.sh" ]; then bash "$dir/$name.sh" "$@"
  elif command -v "$name" >/dev/null 2>&1; then "$name" "$@"
  else return 127; fi
}

# ck_in_story_worktree — 0 inside a linked git worktree checked out on a story/ or fix/
# branch: the shape of a build PARALLEL MODE implementer. Such a worktree sees only its
# own story's frontmatter change, so a board sync from it would push every peer's card
# back to where it stood when the wave was cut. The orchestrator syncs after the merge.
ck_in_story_worktree() {
  local gd cd b
  gd="$(git rev-parse --absolute-git-dir 2>/dev/null)" || return 1
  cd="$(git rev-parse --git-common-dir 2>/dev/null)" || return 1
  cd="$(CDPATH= cd -- "$cd" 2>/dev/null && pwd -P)" || return 1
  gd="$(CDPATH= cd -- "$gd" 2>/dev/null && pwd -P)" || return 1
  [ "$gd" != "$cd" ] || return 1
  b="$(git branch --show-current 2>/dev/null)"
  case "$b" in story/*|fix/*) return 0 ;; esac
  return 1
}
