#!/usr/bin/env bash
# ck-bootstrap — install the committed "ck-code is required here" guard.
#
# A ck-code project keeps its plan, stories and architecture in a layout only the
# plugin maintains (tasks/VERSION.md is its stamp). On a machine that never installed
# ck-code, none of the /ck-code:* commands exist — and nothing in the plugin can say so,
# because the plugin is what is missing.
#
# So the guarantee has to live in the REPO. This script writes two committed things:
#
#   .claude/ck-code-required.sh   a ~1 KB SessionStart hook that fires on any clone
#   .claude/settings.json         wires that hook, and opts the project into the plugin
#
# The guard stays silent on a machine that has ck-code. On one that does not, it turns
# a session that would have quietly improvised around the missing commands into one that
# stops and asks for the install first.
#
# Subcommands: install (idempotent) · check (read-only) · remove
set -u

GUARD_VERSION=1
GUARD_REL=".claude/ck-code-required.sh"
SETTINGS_REL=".claude/settings.json"
GUARD_CMD='"$CLAUDE_PROJECT_DIR"/.claude/ck-code-required.sh'

ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || ROOT=""
[ -n "$ROOT" ] || ROOT=$PWD
GUARD="$ROOT/$GUARD_REL"
SETTINGS="$ROOT/$SETTINGS_REL"

row()  { printf '  %-18s %s\n' "$1" "$2"; }
note() { printf '                     → %s\n' "$1"; }
warn() { printf '  ! %s\n' "$1"; }

usage() {
  cat <<'EOF'
ck-bootstrap — commit the "ck-code is required here" guard into this project

  ck-bootstrap install    write the guard + wire it into .claude/settings.json
  ck-bootstrap check      report guard, settings and delivery state (read-only)
  ck-bootstrap remove     delete the guard and unwire it

The guard only ever speaks on a clone where tasks/VERSION.md exists and ck-code is
not installed. It is useless until committed — `check` says whether it is.
EOF
}

# ---- the guard payload -------------------------------------------------------
# Written verbatim into the project. Keep the emitted additionalContext free of double
# quotes and backslashes: it is spliced into a JSON string with no escaping pass, and a
# guard that emits invalid JSON is a guard the session silently drops.
emit_guard() {
  cat <<EOF
#!/usr/bin/env bash
# ck-code guard — AUTO-GENERATED by ck-bootstrap. DO NOT EDIT BY HAND.
# ck-code-guard: $GUARD_VERSION
#
# Committed with the repo so it runs on ANY clone, including one on a machine that has
# never installed ck-code. This project stores its plan under the ck-code layout
# (tasks/VERSION.md), and every command that reads or writes that state ships with the
# plugin — so a session without it can only improvise around the gap.
#
# Best-effort by design: never fails, never blocks, emits one JSON line or nothing.
EOF
  cat <<'EOF'
cd "${CLAUDE_PROJECT_DIR:-.}" 2>/dev/null || exit 0

# Not a ck-code project → not this guard's business.
[ -f tasks/VERSION.md ] || exit 0

CFG="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
installed=no

# Cheapest first: the plugin puts bin/ on PATH whenever it is live.
command -v ck-index >/dev/null 2>&1 && installed=yes

# A copy vendored into the repo by an older ck-code still provides the commands.
[ "$installed" = no ] && [ -f .claude/skills/ck-code/.claude-plugin/plugin.json ] && installed=yes

# Marketplace install, whatever version and marketplace it came from.
if [ "$installed" = no ]; then
  for p in "$CFG"/plugins/cache/*/ck-code/*/.claude-plugin/plugin.json; do
    [ -f "$p" ] && { installed=yes; break; }
  done
fi
[ "$installed" = no ] && grep -q '"ck-code@' "$CFG/plugins/installed_plugins.json" 2>/dev/null && installed=yes

[ "$installed" = yes ] && exit 0

printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"⛔ ck-code is REQUIRED in this project and is not installed. This repo keeps its plan, stories and architecture in the ck-code layout (tasks/VERSION.md), and every command that reads or writes that state ships with the plugin. STOP before doing anything else here: do not plan, implement, commit, edit tasks/ or docs/architecture/, and never improvise a stand-in for a /ck-code:* command. Give the user these commands and wait: /plugin marketplace add ckandrinirina/ck-code — then /plugin install ck-code@ck-marketplace — then restart the session."}}'
EOF
}

guard_installed_version() {
  [ -f "$GUARD" ] || return 1
  awk '/^# ck-code-guard:/{print $3; exit}' "$GUARD" 2>/dev/null
}

# ---- settings ----------------------------------------------------------------
# Two keys, both of which must be committed to be worth anything:
#   hooks.SessionStart      runs the guard on every clone
#   enabledPlugins          opts this project in, so the install the guard asks for
#                           actually takes effect here without a second manual step
settings_write() {
  mkdir -p "$(dirname "$SETTINGS")"
  if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found — merge this into $SETTINGS_REL by hand:"
    printf '        "enabledPlugins": { "ck-code@ck-marketplace": true },\n'
    printf '        "hooks": { "SessionStart": [ { "hooks": [ { "type": "command", "command": "%s" } ] } ] }\n' "$GUARD_CMD"
    return 1
  fi
  SETTINGS="$SETTINGS" GUARD_CMD="$GUARD_CMD" python3 - <<'PY'
import json, os, sys
path, guard = os.environ['SETTINGS'], os.environ['GUARD_CMD']
data = {}
if os.path.exists(path):
    try:
        with open(path, encoding='utf-8') as fh:
            data = json.load(fh)
    except Exception as exc:
        print('  ! %s is not valid JSON (%s) — left untouched' % (path, exc))
        sys.exit(1)
    if not isinstance(data, dict):
        print('  ! %s is not a JSON object — left untouched' % path)
        sys.exit(1)
changed = []

ep = data.get('enabledPlugins')
if not isinstance(ep, dict):
    ep = {}
if ep.get('ck-code@ck-marketplace') is not True:
    ep['ck-code@ck-marketplace'] = True
    changed.append('enabledPlugins')
data['enabledPlugins'] = ep

hooks = data.get('hooks')
if not isinstance(hooks, dict):
    hooks = {}
sessions = hooks.get('SessionStart')
if not isinstance(sessions, list):
    sessions = []

# Match on the filename, not the whole command: an older guard may have been wired
# with a different prefix, and re-appending would run it twice.
found = None
for entry in sessions:
    if not isinstance(entry, dict):
        continue
    for hook in entry.get('hooks') or []:
        if isinstance(hook, dict) and 'ck-code-required.sh' in str(hook.get('command', '')):
            found = hook
            break
    if found:
        break

if found is None:
    sessions.append({'hooks': [{'type': 'command', 'command': guard}]})
    changed.append('SessionStart hook')
elif found.get('command') != guard:
    found['command'] = guard
    changed.append('SessionStart hook')

hooks['SessionStart'] = sessions
data['hooks'] = hooks

with open(path, 'w', encoding='utf-8') as fh:
    json.dump(data, fh, indent=2, ensure_ascii=False)
    fh.write('\n')
rel = os.path.relpath(path, os.getcwd())
print('  = %s already wired' % rel if not changed else '  ~ %s — %s' % (rel, ', '.join(changed)))
PY
}

settings_drop() {
  [ -f "$SETTINGS" ] || return 0
  command -v python3 >/dev/null 2>&1 || {
    warn "python3 not found — remove the ck-code-required.sh hook from $SETTINGS_REL by hand"; return 1; }
  SETTINGS="$SETTINGS" python3 - <<'PY'
import json, os, sys
path = os.environ['SETTINGS']
try:
    with open(path, encoding='utf-8') as fh:
        data = json.load(fh)
except Exception:
    sys.exit(0)
if not isinstance(data, dict):
    sys.exit(0)
hooks = data.get('hooks')
if isinstance(hooks, dict) and isinstance(hooks.get('SessionStart'), list):
    kept = []
    for entry in hooks['SessionStart']:
        if isinstance(entry, dict):
            inner = [h for h in (entry.get('hooks') or [])
                     if not (isinstance(h, dict) and 'ck-code-required.sh' in str(h.get('command', '')))]
            if not inner:
                continue
            entry['hooks'] = inner
        kept.append(entry)
    if kept:
        hooks['SessionStart'] = kept
    else:
        hooks.pop('SessionStart', None)
    if not hooks:
        data.pop('hooks', None)
with open(path, 'w', encoding='utf-8') as fh:
    json.dump(data, fh, indent=2, ensure_ascii=False)
    fh.write('\n')
print('  ~ %s — SessionStart hook removed' % os.path.relpath(path, os.getcwd()))
PY
}

# ---- delivery ----------------------------------------------------------------
# The guard's whole value is that it travels. Ignored or uncommitted, it protects the one
# machine that already has the plugin and nobody else — the exact case it exists for.
# Reported, never repaired: .gitignore is a file the user wrote for their own reasons.
check_delivery() {
  local rule
  rule=$(git -C "$ROOT" check-ignore -v --no-index "$GUARD_REL" 2>/dev/null | head -1)
  if [ -n "$rule" ]; then
    row "git" "IGNORED by ${rule%%$'\t'*}"
    note "the guard will not be committed, so no clone ever runs it"
    note "git cannot re-include a path under an excluded directory — replace a bare"
    note ".claude/ rule with per-child rules, then negate the two files:"
    printf '\n        .claude/*\n        !.claude/settings.json\n        !.claude/ck-code-required.sh\n\n'
    return 0
  fi
  if git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1 &&
     ! git -C "$ROOT" ls-files --error-unmatch "$GUARD_REL" >/dev/null 2>&1; then
    row "git" "not committed"
    note "run: git add $GUARD_REL $SETTINGS_REL"
  else
    row "git" "committed — travels with the repo"
  fi
}

# ---- subcommands -------------------------------------------------------------
cmd_install() {
  local had
  had=$(guard_installed_version) || had=""
  mkdir -p "$(dirname "$GUARD")"
  emit_guard > "$GUARD" || { warn "could not write $GUARD_REL"; return 1; }
  chmod +x "$GUARD" 2>/dev/null
  if [ -z "$had" ]; then
    row "guard" "$GUARD_REL written (v$GUARD_VERSION)"
  elif [ "$had" = "$GUARD_VERSION" ]; then
    row "guard" "$GUARD_REL already current (v$GUARD_VERSION)"
  else
    row "guard" "$GUARD_REL updated v$had → v$GUARD_VERSION"
  fi
  settings_write
  check_delivery
  return 0
}

cmd_check() {
  local had
  if [ ! -f tasks/VERSION.md ] && [ ! -f "$ROOT/tasks/VERSION.md" ]; then
    row "project" "no tasks/VERSION.md — not a ck-code project"
    return 0
  fi
  had=$(guard_installed_version) || had=""
  if [ -z "$had" ]; then
    row "guard" "MISSING"
    note "run: ck-bootstrap install"
  elif [ "$had" = "$GUARD_VERSION" ]; then
    row "guard" "v$had (current)"
  else
    row "guard" "v$had — stale, current is v$GUARD_VERSION"
    note "run: ck-bootstrap install"
  fi
  if grep -q 'ck-code-required.sh' "$SETTINGS" 2>/dev/null; then
    row "settings" "SessionStart hook wired"
  else
    row "settings" "NOT wired in $SETTINGS_REL"
    note "run: ck-bootstrap install"
  fi
  check_delivery
  return 0
}

cmd_remove() {
  if [ -f "$GUARD" ]; then
    rm -f "$GUARD" && row "guard" "$GUARD_REL deleted"
  else
    row "guard" "not present"
  fi
  settings_drop
  printf '\n  A clone on a machine without ck-code now gets no warning at all.\n'
  return 0
}

case "${1:-check}" in
  install)        shift; cmd_install "$@" ;;
  check|status)   shift 2>/dev/null; cmd_check ;;
  remove)         shift; cmd_remove ;;
  -h|--help|help) usage ;;
  *) printf 'ck-bootstrap: unknown command: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
esac
