#!/usr/bin/env bash
# ck-index.sh — regenerate ck-code's read-only index views from story frontmatter.
#
# The story file frontmatter is the single source of truth (see references/data-model.md).
# This script derives:
#   tasks/<slug>/STORIES_INDEX.md   — one row per story in the plan
#   tasks/FEATURE_INDEX.md          — one row per epic across all plans (rolled up)
#
# Usage:
#   ck-index.sh                 # regenerate every plan + the feature index
#   ck-index.sh tasks/<slug>    # regenerate that plan's index + the feature index
#
# Reads ONLY frontmatter (never story bodies): cheap and deterministic. Run it after
# any change to story frontmatter. Never hand-edit the generated files. Portable to
# bash 3.2 (no associative arrays — all rollup is done in awk).

set -uo pipefail

[ -d tasks ] || { echo "ck-index: no tasks/ directory — nothing to do." >&2; exit 0; }

STAMP="<!-- GENERATED by ck-code scripts/ck-index.sh — DO NOT EDIT. Source of truth: story frontmatter. -->"

FEATURE_ROWS="$(mktemp)"
ROW_CACHE="$(mktemp -d)"
trap 'rm -f "$FEATURE_ROWS"; rm -rf "$ROW_CACHE"' EXIT

# fm KEY FILE — print a frontmatter scalar (between the first --- fences).
fm() {
  awk -v key="$2" '
    FNR==1 && $0!="---" { exit }
    FNR==1 { next }
    $0=="---" { exit }
    { i=index($0,":"); if(i>0){ k=substr($0,1,i-1); v=substr($0,i+1);
        gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v);
        if(k==key){print v; exit} } }
  ' "$1"
}

# Emit STORIES_INDEX rows (stdout) and feature-rollup lines (fd 3) for one plan.
# One awk call over all story files: portable arrays, correct multi-file frontmatter reset.
emit_plan() {
  local plandir="$1"
  local files
  files=$(find "$plandir/epics" -type f -path '*/stories/*.md' 2>/dev/null | sort)
  [ -n "$files" ] || return 0

  # shellcheck disable=SC2016
  printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 awk -v plandir="$plandir" '
    # Emit + accumulate when the closing frontmatter fence is reached (FILENAME is still correct here).
    function emit(   epicdir, eslug, edisp, n, parts, i, w, su, bl, relfile) {
      if (id=="") return
      n=split(FILENAME, parts, "/")
      for (i=1;i<=n;i++) if (parts[i]=="epics" && i+1<=n) { epicdir=parts[i+1]; break }
      eslug=epicdir; sub(/^[0-9]+_/,"",eslug)
      edisp=eslug; gsub(/[_-]/," ",edisp)
      split(edisp, w, " "); edisp="";
      for (i=1;i in w;i++){ edisp=edisp (i>1?" ":"") toupper(substr(w[i],1,1)) substr(w[i],2) }
      su=toupper(status); sub(/IN-PROGRESS/,"IN PROGRESS",su)
      relfile=FILENAME; sub("^"plandir"/","",relfile)
      bl=blocked; sub(/^\[/,"",bl); sub(/\]$/,"",bl); gsub(/^[ \t]+|[ \t]+$/,"",bl); if(bl=="")bl="-"
      printf "S\t| %s · %s | %s | %s | %s | %s | %s | %s |\n", epic, edisp, id, title, su, size, bl, relfile
      eslugOf[epic]=eslug; edispOf[epic]=edisp
      if (status!="skip") total[epic]++
      if (status=="done") { done[epic]++; started[epic]=1 }
      else if (status=="in-progress") { inprog[epic]=1; started[epic]=1 }
      else if (status=="bug") { bug[epic]=1; started[epic]=1 }
    }
    FNR==1 { infm=0; id=title=epic=status=size=blocked="";
             if ($0=="---"){infm=1} next }
    infm && $0=="---" { infm=0; emit(); next }
    infm { i=index($0,":"); if(i>0){ k=substr($0,1,i-1); v=substr($0,i+1);
             gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v);
             if(k=="id")id=v; else if(k=="title")title=v; else if(k=="epic")epic=v;
             else if(k=="status")status=v; else if(k=="size")size=v; else if(k=="blocked_by")blocked=v } }
    END {
      for (e in edispOf) {
        t=total[e]+0; d=done[e]+0; st="TODO"
        if (started[e]) { st=(d==t && !inprog[e] && !bug[e]) ? "DONE" : "IN PROGRESS" }
        printf "F\t%s\t%s\t%s/%s\t%s\t%s\n", e, edispOf[e], d, t, st, eslugOf[e]
      }
    }
  '
}

# plan_rows PLANDIR — print the path to this plan's cached emit_plan output.
# Both consumers below need the same rows, so the awk pass over every story file runs
# ONCE per plan per invocation instead of twice. A plan with no stories caches an empty
# file (emit_plan returns early), so the -f test still short-circuits the second call.
plan_rows() {
  local plandir="$1" cache
  cache="$ROW_CACHE/$(printf '%s' "$plandir" | tr '/.' '__')"
  [ -f "$cache" ] || emit_plan "$plandir" > "$cache"
  printf '%s' "$cache"
}

regen_stories_index() {
  local plandir="$1" rows
  rows="$(plan_rows "$plandir")"
  {
    printf '# Stories Index\n%s\n\n' "$STAMP"
    printf '| Epic | ID | Title | Status | Size | Blocked by | File |\n'
    printf '|------|----|-------|--------|------|------------|------|\n'
    grep '^S	' "$rows" | cut -f2-
  } > "$plandir/STORIES_INDEX.md"
}

# Collect feature rows for a plan into the global accumulator (description + docs added here).
collect_features() {
  local plandir="$1" planname="${1#tasks/}" rows
  rows="$(plan_rows "$plandir")"
  grep '^F	' "$rows" | while IFS=$'\t' read -r _ epic edisp stories st eslug; do
    local docpath="docs/architecture/features/${eslug}/index.md"
    [ -f "$docpath" ] || docpath="—"
    local desc="" epicmd
    epicmd=$(find "$plandir/epics" -maxdepth 2 -name EPIC.md -path "*/${epic}_*" 2>/dev/null | head -1)
    [ -n "$epicmd" ] && desc=$(fm "$epicmd" description)
    printf '%s\t| %s · %s | %s | %s | %s | %s | %s |\n' \
      "$planname" "$epic" "$edisp" "$planname" "$st" "$stories" "$docpath" "$desc" >> "$FEATURE_ROWS"
  done
}

# ---- run ---------------------------------------------------------------------
list_plans() {
  find tasks -maxdepth 2 \( -name PROJECT_OVERVIEW.md -o -name FEATURE_OVERVIEW.md \) 2>/dev/null \
    | sed 's|/[^/]*$||' | sort -u
}

if [ "$#" -ge 1 ]; then
  regen_stories_index "${1%/}"
else
  while IFS= read -r p; do [ -n "$p" ] && regen_stories_index "$p"; done < <(list_plans)
fi

# Feature index always spans every plan so a single-plan run keeps the others' rows.
: > "$FEATURE_ROWS"
while IFS= read -r p; do [ -n "$p" ] && collect_features "$p"; done < <(list_plans)

{
  printf '# Feature Index\n%s\n\n' "$STAMP"
  printf '| Feature | Plan | Status | Stories | Docs | Description |\n'
  printf '|---------|------|--------|---------|------|-------------|\n'
  sort "$FEATURE_ROWS" | cut -f2-
} > tasks/FEATURE_INDEX.md

echo "ck-index: regenerated per-plan STORIES_INDEX.md and tasks/FEATURE_INDEX.md"
