#!/usr/bin/env bash
# ck-index.sh — regenerate ck-code's read-only index views from story frontmatter.
#
# The story file frontmatter is the single source of truth (see references/data-model.md).
# This script derives:
#   tasks/<slug>/STORIES_INDEX.md   — one row per story in the plan
#   tasks/EPICS_INDEX.md            — one row per epic across all plans (rolled up)
#
# Neither view is committed: tasks/.gitignore (written here when missing) keeps them out
# of git, and the session-start hook, ck-view and the status line regenerate them from
# frontmatter whenever they are missing or older than it.
#
# Usage:
#   ck-index.sh                 # regenerate every plan + the epic index
#   ck-index.sh tasks/<slug>    # regenerate that plan's index + the epic index
#
# Reads ONLY frontmatter (never story bodies): cheap and deterministic. Run it after
# any change to story frontmatter. Never hand-edit the generated files. Portable to
# bash 3.2 (no associative arrays — all rollup is done in awk).

set -uo pipefail

CK_HERE="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=scripts/lib/ck-common.sh
. "$CK_HERE/lib/ck-common.sh"

# Locate tasks/ from any subdirectory (a dispatched subagent often runs from one), so a
# run is never a silent no-op.
ck_root || { echo "ck-index: no tasks/ directory (cwd: $PWD) — nothing to do." >&2; exit 0; }

STAMP="<!-- GENERATED by ck-code scripts/ck-index.sh — DO NOT EDIT. Source of truth: story frontmatter. -->"

EPIC_ROWS="$(mktemp)"
ROW_CACHE="$(mktemp -d)"
trap 'rm -f "$EPIC_ROWS"; rm -rf "$ROW_CACHE"' EXIT
trap 'exit 130' INT TERM

# Emit STORIES_INDEX rows (prefix S) and feature-rollup rows (prefix F), both on
# stdout, for one plan. One awk call over all story files: portable arrays, correct
# multi-file frontmatter reset. Malformed stories (no frontmatter fence, unterminated
# frontmatter, missing id) are skipped WITH a warning on stderr — never silently.
emit_plan() {
  local plandir="$1"
  local files
  files=$(find "$plandir/epics" -type f -path '*/stories/*.md' 2>/dev/null | sort)
  [ -n "$files" ] || return 0

  # shellcheck disable=SC2016
  printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 awk -v plandir="$plandir" '
    function warn(msg) { print "ck-index: WARN — " msg > "/dev/stderr" }
    # Strip surrounding quotes: YAML 1.1 reads a bare 01 as octal, so a writer may quote
    # `epic: "01"`. Left raw, the quote would print in every generated cell and break
    # the epic folder lookup.
    function unquote(s) {
      if (s ~ /^".*"$/ || s ~ /^\047.*\047$/) s = substr(s, 2, length(s)-2)
      return s
    }
    # Emit + accumulate when the closing frontmatter fence is reached (FILENAME is still correct here).
    function emit(   epicdir, eslug, edisp, n, parts, i, w, su, bl, relfile, dv, n2, bparts, bi, bp) {
      if (id=="") { warn(FILENAME ": missing id in frontmatter — story skipped"); return }
      n=split(FILENAME, parts, "/")
      for (i=1;i<=n;i++) if (parts[i]=="epics" && i+1<=n) { epicdir=parts[i+1]; break }
      eslug=epicdir; sub(/^[0-9]+_/,"",eslug)
      if (eslug=="") eslug=epicdir
      edisp=eslug; gsub(/[_-]/," ",edisp)
      split(edisp, w, " "); edisp="";
      for (i=1;i in w;i++){ edisp=edisp (i>1?" ":"") toupper(substr(w[i],1,1)) substr(w[i],2) }
      if (edisp=="") edisp=epicdir
      su=toupper(status); sub(/IN-PROGRESS/,"IN PROGRESS",su)
      relfile=substr(FILENAME, length(plandir)+2)
      # blocked_by is raw YAML-flow-list text, e.g. ["02-01", "02-03"]: strip the
      # brackets, split on comma, then unquote each element so the cell renders
      # `02-01, 02-03` instead of `"02-01", "02-03"` (ck-view/ck-project match on
      # the unquoted id).
      bl=blocked; sub(/^\[/,"",bl); sub(/\]$/,"",bl); gsub(/^[ \t]+|[ \t]+$/,"",bl)
      if (bl=="") { bl="-" }
      else {
        n2=split(bl, bparts, ",")
        bl=""
        for (bi=1; bi<=n2; bi++) {
          bp=bparts[bi]; gsub(/^[ \t]+|[ \t]+$/,"",bp); bp=unquote(bp)
          if (bp!="") bl=bl (bl=="" ? "" : ", ") bp
        }
        if (bl=="") bl="-"
      }
      gsub(/\|/,"\\|",title)   # a raw | would break the generated markdown table
      # Delivery cell — the integration axis. Rendered from delivery:/pr: alone; the
      # walk-up to an epic PR is materialized onto the story by `ck-project sync`
      # (references/github-projects.md), so nothing is inherited here.
      dv="-"
      if (delivery=="merged") dv="MERGED"
      else if (delivery=="direct") dv="DIRECT"
      else if (delivery=="pr") dv=(pr!="" ? "PR #" pr : "PR")
      printf "S\t| %s · %s | %s | %s | %s | %s | %s | %s | %s |\n", epic, edisp, id, title, su, dv, size, bl, relfile
      eslugOf[epic]=eslug; edispOf[epic]=edisp
      if (status!="skip") total[epic]++
      if (status=="done") { done[epic]++; started[epic]=1
                            # DIRECT reached the trunk without a PR — same arrival as
                            # MERGED, so it counts toward the epic rollup identically.
                            if (delivery=="merged" || delivery=="direct") merged[epic]++ }
      else if (status=="in-progress") { inprog[epic]=1; started[epic]=1 }
      else if (status=="bug") { bug[epic]=1; started[epic]=1 }
    }
    FNR==1 { if (infm) warn(prevfile ": unterminated frontmatter — story skipped")
             prevfile=FILENAME; infm=0; id=title=epic=status=size=blocked=delivery=pr="";
             sub(/\r$/,"")
             if ($0=="---"){infm=1} else warn(FILENAME ": no frontmatter fence — story skipped")
             next }
    { sub(/\r$/,"") }
    infm && $0=="---" { infm=0; emit(); next }
    infm { i=index($0,":"); if(i>0){ k=substr($0,1,i-1); v=substr($0,i+1);
             gsub(/^[ \t]+|[ \t]+$/,"",k); gsub(/^[ \t]+|[ \t]+$/,"",v);
             if(k=="id")id=unquote(v); else if(k=="title")title=unquote(v); else if(k=="epic")epic=unquote(v);
             else if(k=="status")status=unquote(v); else if(k=="size")size=unquote(v); else if(k=="blocked_by")blocked=v;
             else if(k=="delivery")delivery=unquote(v); else if(k=="pr")pr=unquote(v) } }
    END {
      if (infm) warn(prevfile ": unterminated frontmatter — story skipped")
      for (e in edispOf) {
        t=total[e]+0; d=done[e]+0; m=merged[e]+0; st="TODO"
        # MERGED is DONE plus "all of it reached the trunk". Both are finished states —
        # every unfinished set excludes both (references/feature-index.md). NOTE: no
        # apostrophes in this awk body; it is a single-quoted shell string.
        if (started[e]) {
          if (d==t && !inprog[e] && !bug[e]) st=(m==t) ? "MERGED" : "DONE"
          else st="IN PROGRESS"
        }
        printf "F\t%s\t%s\t%s/%s\t%s\t%s\n", e, edispOf[e], d, t, st, eslugOf[e]
      }
    }
  '
}

# plan_rows PLANDIR — print the path to this plan's cached emit_plan output.
# Both consumers below need the same rows, so the awk pass over every story file runs
# ONCE per plan per invocation instead of twice. A plan with no stories caches an empty
# file (emit_plan returns early), so the -f test still short-circuits the second call.
plan_rows() {
  local plandir="$1" cache
  cache="$ROW_CACHE/$(printf '%s' "$plandir" | tr '/.' '__')"
  [ -f "$cache" ] || emit_plan "$plandir" > "$cache"
  printf '%s' "$cache"
}

regen_stories_index() {
  local plandir="$1" rows
  rows="$(plan_rows "$plandir")"
  {
    printf '# Stories Index\n%s\n\n' "$STAMP"
    printf '| Epic | ID | Title | Status | Delivery | Size | Blocked by | File |\n'
    printf '|------|----|-------|--------|----------|------|------------|------|\n'
    grep '^S	' "$rows" | cut -f2-
  } | ck_write_atomic "$plandir/STORIES_INDEX.md"
}

# Collect epic rows for a plan into the global accumulator (description + docs added here).
# The Docs cell prefers the EPIC.md `slug:` frontmatter over the folder-derived slug, so an
# epic can route to the feature doc that owns it (several epics may share one feature doc).
collect_epics() {
  local plandir="$1" planname="${1#tasks/}" rows
  rows="$(plan_rows "$plandir")"
  # IFS=tab alone collapses runs, so an empty middle field would shift every later
  # variable; -d '' with a sentinel keeps positions exact.
  grep '^F	' "$rows" | while IFS= read -r frow; do
    epic=$(printf '%s' "$frow" | cut -f2); edisp=$(printf '%s' "$frow" | cut -f3)
    stories=$(printf '%s' "$frow" | cut -f4); st=$(printf '%s' "$frow" | cut -f5)
    eslug=$(printf '%s' "$frow" | cut -f6)
    local desc="" fmslug="" epicmd
    epicmd=$(find "$plandir/epics" -maxdepth 2 -name EPIC.md -path "*/${epic}_*" 2>/dev/null | head -1)
    if [ -n "$epicmd" ]; then
      desc=$(ck_fm "$epicmd" description)
      desc=${desc//|/\\|}
      fmslug=$(ck_fm "$epicmd" slug)
      [ -n "$fmslug" ] && eslug="$fmslug"
    fi
    local docpath="docs/architecture/features/${eslug}/index.md"
    [ -f "$docpath" ] || docpath="—"
    printf '%s\t| %s · %s | %s | %s | %s | %s | %s |\n' \
      "$planname" "$epic" "$edisp" "$planname" "$st" "$stories" "$docpath" "$desc" >> "$EPIC_ROWS"
  done
}

# ---- run ---------------------------------------------------------------------
list_plans() { ck_plans; }

if [ "$#" -ge 1 ]; then
  PLAN="${1%/}"
  if [ ! -d "$PLAN" ]; then
    echo "ck-index: ERROR — no such plan directory: $PLAN (usage: ck-index.sh [tasks/<slug>])" >&2
    exit 1
  fi
  regen_stories_index "$PLAN"
else
  while IFS= read -r p; do [ -n "$p" ] && regen_stories_index "$p"; done < <(list_plans)
fi

# The epic index always spans every plan — recomputed fresh from every plan's rows on each
# run. A single-plan run refreshes only that plan's STORIES_INDEX.md.
: > "$EPIC_ROWS"
while IFS= read -r p; do [ -n "$p" ] && collect_epics "$p"; done < <(list_plans)

{
  printf '# Epics Index\n%s\n\n' "$STAMP"
  printf '| Epic | Plan | Status | Stories | Docs | Description |\n'
  printf '|------|------|--------|---------|------|-------------|\n'
  sort "$EPIC_ROWS" | cut -f2-
} | ck_write_atomic tasks/EPICS_INDEX.md

# The views are generated, never committed. Written once; a user's own edits to the
# file are kept, because only a missing file is replaced.
if [ ! -f tasks/.gitignore ]; then
  printf '%s\n' "# Generated by ck-code. The views regenerate from story frontmatter; never commit them." \
    "STORIES_INDEX.md" "EPICS_INDEX.md" > tasks/.gitignore
fi

echo "ck-index: regenerated per-plan STORIES_INDEX.md and tasks/EPICS_INDEX.md"
