#!/usr/bin/env bash
# ck-view.sh — render ck-code's read-only dashboards from the generated indexes.
#
# The counterpart to ck-index.sh: that script WRITES the generated views from story
# frontmatter, this one READS them and renders. Everything here is a pure function of
# `tasks/<slug>/STORIES_INDEX.md` — no judgement, no prose, nothing a model needs to
# re-derive — so it costs zero tokens to compute and cannot make an arithmetic or
# dependency-resolution mistake.
#
# Usage:
#   ck-view.sh status   [tasks/<slug>]   # full dashboard (default)
#   ck-view.sh next     [tasks/<slug>]   # the next ready story + Also Ready
#   ck-view.sh progress [tasks/<slug>]   # epic rollup, by-size, bottlenecks, milestones
#   ck-view.sh state                     # project-state probe + counts + routing verdict
#   ck-view.sh waves --epic NN           # dependency-ordered wave plan for one epic
#
# The Ready rule (skills/guide/SKILL.md) is implemented ONCE, here: a story is ready iff
# `status: todo` and every `blocked_by` id resolves to `done`, OR `status: bug`. Blockers
# resolve across ALL plans, because story ids are globally unique in v6 and `blocked_by`
# may name a story in another plan (references/data-model.md).
#
# `status`/`next`/`progress`/`waves` regenerate a missing or unstamped index first (a
# read-only regeneration of a projection — it invents no state). `state` NEVER does:
# /ck-code:guide writes nothing at all.

set -uo pipefail

# Locate tasks/: fall back to the git repo root so a run from a subdirectory
# (e.g. a dispatched subagent) is never a silent no-op.
if [ ! -d tasks ]; then
  ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
  if [ -n "$ROOT" ] && [ -d "$ROOT/tasks" ]; then
    cd "$ROOT"
  elif [ "${1:-status}" != "state" ]; then
    echo "ck-view: no tasks/ directory (cwd: $PWD) — run /ck-code:plan first." >&2
    exit 0
  fi
fi

usage() {
  sed -n '3,25p' "$0" | sed 's/^# \{0,1\}//'
}

MODE="status"
[ "$#" -ge 1 ] && { MODE="$1"; shift; }
PLAN_ARG=""
EPIC_ARG=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --epic)   EPIC_ARG="${2:-}"; shift 2 || shift ;;
    --epic=*) EPIC_ARG="${1#*=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    tasks/*)  PLAN_ARG="${1%/}"; shift ;;
    *)        echo "ck-view: WARN — ignoring unrecognised argument: $1" >&2; shift ;;
  esac
done

case "$MODE" in
  status|next|progress|state|waves) ;;
  -h|--help) usage; exit 0 ;;
  *) echo "ck-view: ERROR — unknown mode: $MODE (status|next|progress|state|waves)" >&2; exit 1 ;;
esac

if [ -n "$PLAN_ARG" ] && [ ! -d "$PLAN_ARG" ]; then
  echo "ck-view: ERROR — no such plan directory: $PLAN_ARG" >&2
  exit 1
fi

TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT
trap 'exit 130' INT TERM

STAMP_MARK="GENERATED by ck-code"

list_plans() {
  find tasks -maxdepth 2 \( -name PROJECT_OVERVIEW.md -o -name FEATURE_OVERVIEW.md \) 2>/dev/null \
    | sed 's|/[^/]*$||' | sort -u
}

# ck-index may be on PATH (plugin bin/) or beside this script; prefer the sibling so a
# Workflow subagent with an empty $CLAUDE_PLUGIN_ROOT still regenerates correctly.
run_index() {
  local here; here="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
  if [ -x "$here/ck-index.sh" ]; then "$here/ck-index.sh" "$@" >/dev/null 2>&1
  elif command -v ck-index >/dev/null 2>&1; then ck-index "$@" >/dev/null 2>&1
  else return 1; fi
}

# ensure_index PLANDIR — regenerate when the view is missing or lost its stamp.
ensure_index() {
  local p="$1"
  [ "$MODE" = "state" ] && return 0
  if [ ! -f "$p/STORIES_INDEX.md" ] || ! grep -q "$STAMP_MARK" "$p/STORIES_INDEX.md" 2>/dev/null; then
    run_index "$p" || {
      echo "ck-view: WARN — $p/STORIES_INDEX.md is missing or unstamped and ck-index could not be run." >&2
      return 1
    }
    echo "ck-view: regenerated $p/STORIES_INDEX.md (was missing or unstamped)." >&2
  fi
  return 0
}

# load_rows — emit one TSV row per story across every plan:
#   plan  epicnum  epicdisp  id  title  STATUS  DELIVERY  SIZE  blocked  relfile
# Only rows whose ID cell reads EE-SS are accepted, so the header and separator lines
# of the markdown table can never be mistaken for stories. ck-index escapes a literal
# pipe in a title as `\|`; that is neutralised before the split and restored after,
# otherwise the escape would be counted as a column boundary and shift every later cell.
load_rows() {
  local p
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    ensure_index "$p"
    [ -f "$p/STORIES_INDEX.md" ] || continue
    awk -v plan="$p" '
      /^\|/ {
        line=$0; gsub(/\\\|/,"\001",line)
        n=split(line,f,"|")
        if (n<10) next
        for (i=1;i<=n;i++) { gsub(/^[ \t]+|[ \t]+$/,"",f[i]); gsub(/\001/,"|",f[i]) }
        if (f[3] !~ /^[0-9]+-[0-9]+$/) next
        epic=f[2]; edisp=""
        if (match(epic, / · /)) { edisp=substr(epic, RSTART+RLENGTH); epic=substr(epic,1,RSTART-1) }
        gsub(/^[ \t]+|[ \t]+$/,"",epic); gsub(/^[ \t]+|[ \t]+$/,"",edisp)
        if (edisp=="") edisp="Epic " epic
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", \
          plan, epic, edisp, f[3], f[4], f[5], f[6], f[7], f[8], f[9]
      }
    ' "$p/STORIES_INDEX.md"
  done < <(list_plans) | sort -t "$(printf '\t')" -k2,2 -k4,4
}

# plan_name PLANDIR — the first `# ` heading of the plan overview, else the folder name.
plan_name() {
  local p="$1" f n
  for f in "$p/PROJECT_OVERVIEW.md" "$p/FEATURE_OVERVIEW.md"; do
    [ -f "$f" ] || continue
    n=$(awk '/^# /{sub(/^# +/,""); print; exit}' "$f")
    [ -n "$n" ] && { printf '%s' "$n"; return; }
  done
  printf '%s' "${p#tasks/}"
}

# Shared awk preamble: the Ready rule, the progress bar, and the maps every mode needs.
read -r -d '' AWK_COMMON <<'AWKEOF' || true
  function trim(s) { gsub(/^[ \t]+|[ \t]+$/,"",s); return s }
  function bar(d, t, w,   i, filled, s) {
    filled = (t>0) ? int(d*w/t) : 0
    s = "["
    for (i=0;i<w;i++) s = s ((i<filled) ? "=" : "-")
    return s "]"
  }
  function pct(d, t) { return (t>0) ? int(d*100/t + 0.5) : 0 }
  function plural(n) { return (n==1) ? "story" : "stories" }
  # ready(id) — the single Ready rule. BUG is always actionable; TODO needs every
  # blocker DONE. Anything else (in-progress, done, skip) is not ready.
  function ready(i,   n, a, j, b) {
    if (st[i]=="BUG") return 1
    if (st[i]!="TODO") return 0
    if (bl[i]=="" || bl[i]=="-") return 1
    n = split(bl[i], a, ",")
    for (j=1;j<=n;j++) { b=trim(a[j]); if (b=="") continue; if (st[b]!="DONE") return 0 }
    return 1
  }
  # unmet(id) — the blockers holding a story back, comma-joined ("" when none).
  function unmet(i,   n, a, j, b, out) {
    if (bl[i]=="" || bl[i]=="-") return ""
    n = split(bl[i], a, ","); out=""
    for (j=1;j<=n;j++) { b=trim(a[j]); if (b=="") continue
      if (st[b]!="DONE") out = out (out==""?"":", ") b (b in st ? "" : " (unknown)") }
    return out
  }
  {
    N++
    plan[N]=$1; ep[N]=$2; edisp[N]=$3; id[N]=$4; ttl[N]=$5
    stt[N]=$6; dlv[N]=$7; sz[N]=$8; blk[N]=$9; rel[N]=$10
    st[$4]=$6; bl[$4]=$9
    if ($9!="" && $9!="-") { n=split($9,a,","); for (j=1;j<=n;j++) { b=trim(a[j]); if (b!="") blocks[b]++ } }
  }
AWKEOF

# ---------------------------------------------------------------- status ------
render_status() {
  local p="$1" name; name="$(plan_name "$p")"
  awk -v want="$p" -v projname="$name" -F '\t' "
$AWK_COMMON
"'
  END {
    for (i=1;i<=N;i++) if (plan[i]==want) {
      if (stt[i]=="SKIP") { skipped++; continue }
      tot++
      if (stt[i]=="DONE") { d++
        if (dlv[i]=="MERGED" || dlv[i]=="DIRECT") c_merged++
        else if (dlv[i] ~ /^PR/) c_review++
        else c_unshipped++ }
      else if (stt[i]=="IN PROGRESS") c_ip++
      else if (stt[i]=="BUG") c_bug++
      else if (ready(id[i])) c_ready++
      else c_blocked++
      if (!(ep[i] in seen)) { seen[ep[i]]=1; nepics++; order[nepics]=ep[i] }
      etot[ep[i]]++; if (stt[i]=="DONE") edone[ep[i]]++
      ename[ep[i]]=edisp[i]
    }
    if (tot==0) { print "No stories in " want " yet. Run /ck-code:plan to generate them."; exit }

    printf "## Project Progress: %s\n\n", projname
    printf "**Plan:** %s\n", want
    printf "**Total:** %d epics, %d stories\n", nepics, tot
    printf "**Progress:** %d/%d stories (%d%%)\n\n", d, tot, pct(d,tot)
    printf "%s %d%%\n", bar(d,tot,38), pct(d,tot)

    for (k=1;k<=nepics;k++) {
      e=order[k]
      printf "\n### Epic %s: %s (%d/%d)\n", e, ename[e], edone[e]+0, etot[e]+0
      printf "%s %d%%\n", bar(edone[e]+0, etot[e]+0, 20), pct(edone[e]+0, etot[e]+0)
      for (i=1;i<=N;i++) {
        if (plan[i]!=want || ep[i]!=e) continue
        s=stt[i]
        if (s=="SKIP")             { icon="[-]"; note="SKIPPED" }
        else if (s=="BUG")         { icon="[\xF0\x9F\x90\x9B]"; note="BUG" }
        else if (s=="DONE")        { icon="[x]"; note="DONE" }
        else if (s=="IN PROGRESS") { icon="[>]"; note="IN PROGRESS" }
        else if (ready(id[i]))     { icon="[ ]"; note="TODO (ready)" }
        else                       { icon="[~]"; note="TODO (blocked by " unmet(id[i]) ")" }
        if (s=="DONE" || s=="BUG") {
          if (dlv[i]=="MERGED")      note=note " · merged"
          else if (dlv[i]=="DIRECT") note=note " · merged (direct)"
          else if (dlv[i] ~ /^PR/)   note=note " · " dlv[i]
          else if (s=="DONE")        note=note " · not shipped"
        }
        printf "  %s %s: %s (%s) — %s\n", icon, id[i], ttl[i], sz[i], note
      }
    }

    print "\n### Summary"
    printf "- DONE · merged: %d %s\n", c_merged+0, plural(c_merged+0)
    printf "- DONE · in review: %d %s\n", c_review+0, plural(c_review+0)
    printf "- DONE · not shipped: %d %s\n", c_unshipped+0, plural(c_unshipped+0)
    printf "- IN PROGRESS: %d %s\n", c_ip+0, plural(c_ip+0)
    printf "- TODO (ready): %d %s\n", c_ready+0, plural(c_ready+0)
    printf "- TODO (blocked): %d %s\n", c_blocked+0, plural(c_blocked+0)
    printf "- BUG: %d %s\n", c_bug+0, plural(c_bug+0)
    if (skipped) printf "- SKIPPED: %d %s (excluded from totals)\n", skipped, plural(skipped)

    print "\n### Quick Actions"
    print "- Next story: /ck-code:track next"
    print "- Full progress: /ck-code:track progress"
  }' "$TSV"
}

# ------------------------------------------------------------------ next ------
render_next() {
  local filter="${1:-}"
  local pick
  pick=$(awk -v want="$filter" -F '\t' "
$AWK_COMMON
"'
  END {
    best=0
    for (i=1;i<=N;i++) {
      if (want!="" && plan[i]!=want) continue
      if (!ready(id[i])) continue
      nready++
      rank = (stt[i]=="BUG") ? 0 : 1
      key = sprintf("%d|%s", rank, id[i])
      if (best==0 || key < bestkey) { best=i; bestkey=key }
      cand[++nc]=i
    }
    if (best==0) { print "NONE"; exit }
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%d\t%d\n", \
      plan[best], id[best], ttl[best], edisp[best], sz[best], stt[best], \
      plan[best] "/" rel[best], blocks[id[best]]+0, nready
    for (j=1;j<=nc;j++) if (cand[j]!=best) \
      printf "ALSO\t%s\t%s\t%s\t%s\n", id[cand[j]], ttl[cand[j]], sz[cand[j]], stt[cand[j]]
  }' "$TSV")

  if [ "$pick" = "NONE" ] || [ -z "$pick" ]; then
    echo "## No Stories Ready"
    echo
    echo "All remaining TODO stories are blocked by incomplete dependencies."
    echo
    echo "### Blocking Chain"
    awk -v want="${filter}" -F '\t' "
$AWK_COMMON
"'
    END {
      for (i=1;i<=N;i++) {
        if (want!="" && plan[i]!=want) continue
        if (stt[i]=="DONE" || stt[i]=="SKIP") continue
        if (blocks[id[i]]+0 == 0) continue
        held=""
        for (j=1;j<=N;j++) { u=unmet(id[j]); if (u ~ ("(^|, )" id[i] "($|,)")) held = held (held==""?"":", ") id[j] }
        if (held!="") { printf "- %s (%s) blocks: %s\n", id[i], stt[i], held; any=1 }
      }
      if (!any) print "- No unfinished story blocks another — nothing is scheduled at all."
    }' "$TSV"
    echo
    echo "Complete the IN PROGRESS stories first, then more will unblock."
    return 0
  fi

  local plan id title epic size status path unblocks nready
  IFS=$'\t' read -r plan id title epic size status path unblocks nready <<<"$(printf '%s' "$pick" | head -1)"

  local why
  if [ "$status" = "BUG" ]; then
    why="Open bug in built code — a diagnosed bug outranks new work (Bug-Fix Mode)"
  elif [ "${unblocks:-0}" -gt 0 ]; then
    why="First ready story in $epic; unblocks $unblocks other stor$([ "$unblocks" -eq 1 ] && echo y || echo ies)"
  else
    why="First ready story in $epic"
  fi

  echo "## Next Story to Implement"
  echo
  printf '**Recommended:** %s — %s\n' "$id" "$title"
  printf '**Epic:** %s\n' "$epic"
  printf '**Size:** %s\n' "$size"
  printf '**Why this one:** %s\n' "$why"
  echo
  echo "### Acceptance Criteria Preview"
  awk '/^## Acceptance Criteria/{f=1;next} f&&/^## /{exit} f&&/^[ \t]*- /{print; n++; if(n>=6) exit}' "$path" \
    | sed 's/^[ \t]*/- /;s/^- - /- /' || true
  grep -q '^## Acceptance Criteria' "$path" 2>/dev/null || echo "- (no Acceptance Criteria section in the story file)"
  echo
  echo "### Files to Touch"
  awk 'FNR==1&&$0!="---"{exit} FNR==1{next} $0=="---"{exit}
       /^files:/{sub(/^files:[ \t]*/,""); gsub(/^\[|\]$/,"");
                 n=split($0,a,","); for(i=1;i<=n;i++){gsub(/^[ \t]+|[ \t]+$/,"",a[i]); if(a[i]!="")print "- " a[i]}}' "$path"
  echo
  echo "**Implement now?**"
  printf 'Run: /ck-code:build %s\n' "$path"

  local also
  also=$(printf '%s' "$pick" | awk -F '\t' '$1=="ALSO"{printf "- %s: %s (%s)%s\n", $2, $3, $4, ($5=="BUG"?" 🐛":"")}')
  if [ -n "$also" ]; then
    echo
    printf '### Also Ready (%d more)\n' "$(printf '%s\n' "$also" | grep -c .)"
    printf '%s\n' "$also"
  fi
  echo
  printf 'NEXT: /ck-code:build %s\n' "$path"
}

# -------------------------------------------------------------- progress ------
render_progress() {
  local p="$1" name; name="$(plan_name "$p")"
  local roadmap="$p/ROADMAP.md"
  [ -f "$roadmap" ] || roadmap=/dev/null
  awk -v want="$p" -v projname="$name" -v today="$(date +%Y-%m-%d)" -v roadmap="$roadmap" -F '\t' "
$AWK_COMMON
"'
  END {
    for (i=1;i<=N;i++) if (plan[i]==want) {
      if (stt[i]=="SKIP") continue
      tot++; if (stt[i]=="DONE") d++
      s=sz[i]; if (s=="") s="?"
      if (!(s in seensz)) { seensz[s]=1; szorder[++nsz]=s }
      sztot[s]++; if (stt[i]=="DONE") szdone[s]++
      if (!(ep[i] in seen)) { seen[ep[i]]=1; order[++ne]=ep[i]; ename[ep[i]]=edisp[i] }
      etot[ep[i]]++; if (stt[i]=="DONE") edone[ep[i]]++
      if (stt[i]=="TODO" && !ready(id[i])) nblocked++
    }
    if (tot==0) { print "No stories in " want " yet. Run /ck-code:plan to generate them."; exit }

    printf "## Project Progress Report\n\n"
    printf "**Project:** %s\n", projname
    printf "**Plan:** %s\n", want
    printf "**As of:** %s\n\n", today
    print "### Overall"
    printf "%s %d%%\n", bar(d,tot,40), pct(d,tot)
    printf "%d/%d stories complete\n\n", d, tot

    print "### By Size"
    print "| Size | Done | Total | Remaining |"
    print "|------|------|-------|-----------|"
    for (k=1;k<=nsz;k++) { s=szorder[k]
      printf "| %s | %d | %d | %d |\n", s, szdone[s]+0, sztot[s]+0, sztot[s]-szdone[s] }

    print "\n### By Epic"
    print "| Epic | Title | Done | Total | Progress |"
    print "|------|-------|------|-------|----------|"
    for (k=1;k<=ne;k++) { e=order[k]
      printf "| %s | %s | %d | %d | %s %d%% |\n", e, ename[e], edone[e]+0, etot[e]+0, \
        bar(edone[e]+0, etot[e]+0, 10), pct(edone[e]+0, etot[e]+0) }

    print "\n### Bottlenecks"
    printf "- %d stor%s waiting on dependencies\n", nblocked+0, (nblocked==1?"y":"ies")
    topn=0; top=""
    for (i=1;i<=N;i++) if (plan[i]==want && stt[i]!="DONE" && stt[i]!="SKIP" && blocks[id[i]]+0>topn) { topn=blocks[id[i]]+0; top=id[i] }
    if (topn>0) printf "- Biggest blocker: %s — blocks %d other stor%s\n", top, topn, (topn==1?"y":"ies")
    else print "- No unfinished story blocks another"

    # Milestone tracker — only when ROADMAP.md actually carries a `## Milestones` table.
    if (roadmap != "/dev/null") {
      inms=0; nms=0
      while ((getline line < roadmap) > 0) {
        if (line ~ /^## /) { inms = (line ~ /^## +Milestones/) ; continue }
        if (!inms || line !~ /^\|/) continue
        nf=split(line, c, "|")
        if (nf<4) continue
        nm=c[2]; epics=c[3]
        gsub(/^[ \t]+|[ \t]+$/,"",nm); gsub(/^[ \t]+|[ \t]+$/,"",epics)
        if (nm=="" || nm ~ /^-+$/ || tolower(nm)=="milestone") continue
        ndone=0; ntot=0; list=""
        m=split(epics, ee, /[^0-9]+/)
        for (x=1;x<=m;x++) { v=ee[x]; if (v=="") continue
          if (length(v)==1) v="0" v
          if (!(v in seen)) continue
          ntot++; list = list (list==""?"":", ") "Epic " v
          if (edone[v]+0 == etot[v]+0 && etot[v]+0 > 0) ndone++ }
        if (ntot==0) continue
        if (nms++ == 0) { print "\n### Milestone Tracker (from ROADMAP.md)"
                          print "| Milestone | Status | Epics |"
                          print "|-----------|--------|-------|" }
        printf "| %s | %d/%d epics done | %s |\n", nm, ndone, ntot, list
      }
      close(roadmap)
    }
  }' "$TSV"
}

# ----------------------------------------------------------------- state ------
render_state() {
  local n_specs n_arch n_team n_tasks n_idx ds_linked ds_pending
  n_specs=$(ls -d docs/specs/*/ 2>/dev/null | grep -c . || true)
  n_arch=$(find docs/architecture -name '*.md' 2>/dev/null | head -1 | grep -c . || true)
  n_team=$(ls -d .claude/skills/expert-*/ .claude/skills/guide-*/ 2>/dev/null | grep -c . || true)
  n_tasks=$(ls -d tasks/*/ 2>/dev/null | grep -c . || true)
  n_idx=0
  if [ -f tasks/FEATURE_INDEX.md ] && ls tasks/*/STORIES_INDEX.md >/dev/null 2>&1; then n_idx=1; fi
  ds_linked=0; [ -d docs/architecture/design-system ] && ds_linked=1
  ds_pending=$(grep -l '"awaiting-link"' docs/specs/*/.metadata.json 2>/dev/null | grep -c . || true)

  local counts
  counts=$(awk -F '\t' "
$AWK_COMMON
"'
  END {
    for (i=1;i<=N;i++) {
      if (stt[i]=="SKIP") continue
      if (stt[i]=="DONE") { done++
        if (dlv[i]=="MERGED" || dlv[i]=="DIRECT") merged++
        else if (dlv[i] ~ /^PR/) review++
        else unshipped++ }
      else if (stt[i]=="IN PROGRESS") ip++
      else if (stt[i]=="BUG") bug++
      else if (ready(id[i])) rdy++
      else blocked++
    }
    printf "%d %d %d %d %d %d %d %d", rdy+0, bug+0, blocked+0, ip+0, done+0, unshipped+0, review+0, merged+0
  }' "$TSV")
  set -- $counts
  local ready=${1:-0} bug=${2:-0} blocked=${3:-0} ip=${4:-0} done=${5:-0} unshipped=${6:-0} review=${7:-0} merged=${8:-0}
  local total=$((ready + bug + blocked + ip + done))

  local cmd why
  if [ "$n_arch" -eq 0 ] && [ "$n_specs" -eq 0 ]; then
    cmd='/ck-code:spec "<feature description>"'
    why='no spec and no architecture — start with a stakeholder-friendly spec, or skip to /ck-code:design <spec-file> if a written spec already exists'
  elif [ "$n_arch" -eq 0 ]; then
    cmd='/ck-code:design <spec-file>'; why='specs exist but no architecture docs — refine the spec into architecture'
  elif [ "$n_team" -eq 0 ]; then
    cmd='/ck-code:team'; why='architecture exists but no project-tailored expert/guide skills'
  elif [ "$n_tasks" -eq 0 ]; then
    cmd='/ck-code:plan <spec-file>'; why='architecture and team skills exist but nothing is planned'
  elif [ "$n_idx" -eq 0 ]; then
    cmd='/ck-code:track'; why='tasks/ exists but the generated indexes are missing — track regenerates them'
  elif [ "$bug" -gt 0 ]; then
    cmd='/ck-code:track next'; why="$bug open bug(s) — a diagnosed bug outranks new work (Bug-Fix Mode)"
  elif [ "$ready" -gt 0 ]; then
    cmd='/ck-code:track next'; why="$ready ready stor$([ "$ready" -eq 1 ] && echo y || echo ies) to implement"
  elif [ "$ip" -gt 0 ]; then
    cmd='/ck-code:ship <story-path>'; why="$ip in-progress stor$([ "$ip" -eq 1 ] && echo y || echo ies) and nothing else ready"
  elif [ "$unshipped" -gt 0 ]; then
    cmd='/ck-code:ship <story-path>'; why="$unshipped finished stor$([ "$unshipped" -eq 1 ] && echo y || echo ies) with no PR — nothing is on the trunk until they ship"
  elif [ "$done" -gt 0 ]; then
    cmd='/ck-code:track progress'; why="all work is done ($review still awaiting merge) — review the milestones or plan the next feature"
  elif [ "$n_tasks" -gt 0 ]; then
    cmd='/ck-code:plan'; why='tasks/ exists but carries no story rows — re-check tasks/<slug>/'
  else
    cmd='/ck-code:plan'; why='nothing planned yet'
  fi

  local dscell='—'
  [ "$ds_linked" -eq 1 ] && dscell='linked'
  [ "$ds_linked" -eq 0 ] && [ "$ds_pending" -gt 0 ] && dscell="$ds_pending awaiting link"

  echo "## ck-code: project state"
  echo
  echo "| Check | Value |"
  echo "|---|---|"
  printf '| docs/specs/        | %s |\n' "$([ "$n_specs" -gt 0 ] && echo "has ($n_specs)" || echo '—')"
  printf '| docs/architecture/ | %s |\n' "$([ "$n_arch" -gt 0 ] && echo 'has' || echo '—')"
  printf '| .claude/skills/    | %s |\n' "$([ "$n_team" -gt 0 ] && echo "$n_team" || echo '—')"
  printf '| tasks/             | %s |\n' "$([ "$n_tasks" -gt 0 ] && echo "has ($n_tasks)" || echo '—')"
  printf '| generated indexes  | %s |\n' "$([ "$n_idx" -gt 0 ] && echo 'has' || echo '—')"
  printf '| Claude Design      | %s |\n' "$dscell"
  if [ "$total" -gt 0 ]; then
    printf '| Stories            | %s ready · %s bug · %s blocked · %s IP · %s done |\n' \
      "$ready" "$bug" "$blocked" "$ip" "$done"
  else
    printf '| Stories            | — |\n'
  fi
  echo
  printf 'FLAGS: specs=%s architecture=%s team_skills=%s tasks=%s indexes=%s ds_linked=%s ds_pending=%s\n' \
    "$n_specs" "$n_arch" "$n_team" "$n_tasks" "$n_idx" "$ds_linked" "$ds_pending"
  printf 'COUNTS: ready=%s bug=%s blocked=%s in_progress=%s done=%s unshipped=%s in_review=%s merged=%s\n' \
    "$ready" "$bug" "$blocked" "$ip" "$done" "$unshipped" "$review" "$merged"
  printf 'RECOMMEND: %s\n' "$cmd"
  printf 'WHY: %s\n' "$why"
}

# ----------------------------------------------------------------- waves ------
render_waves() {
  local epic="$1"
  case "$epic" in ""|*[!0-9]*) echo "ck-view: ERROR — waves needs --epic NN (digits only)" >&2; exit 1 ;; esac
  [ "${#epic}" -eq 1 ] && epic="0$epic"

  local dirs n
  dirs=$(find tasks -mindepth 3 -maxdepth 3 -type d -path "tasks/*/epics/${epic}_*" 2>/dev/null)
  n=$(printf '%s\n' "$dirs" | grep -c . || true)
  if [ "$n" -eq 0 ]; then
    echo "ck-view: ERROR — no epic $epic in tasks/. Epics present:" >&2
    find tasks -mindepth 3 -maxdepth 3 -type d -path 'tasks/*/epics/*' 2>/dev/null \
      | sed 's|.*/epics/||' | sort >&2
    exit 1
  fi
  if [ "$n" -gt 1 ]; then
    echo "ck-view: ERROR — epic $epic exists in more than one plan (colliding epic numbers). Run /ck-code:migrate; never pick one." >&2
    printf '%s\n' "$dirs" >&2
    exit 1
  fi
  local plan; plan=$(printf '%s' "$dirs" | sed 's|/epics/.*||')

  # files: per story — frontmatter only, one bounded awk over the epic's story files.
  local FILESMAP; FILESMAP="$(mktemp)"
  find "$plan/epics/${epic}_"*/stories -name '*.md' 2>/dev/null | sort | while IFS= read -r f; do
    awk -v f="$f" '
      FNR==1 && $0!="---" { exit } FNR==1 { next } $0=="---" { exit }
      /^id:/ { sub(/^id:[ \t]*/,""); gsub(/["\x27]/,""); gsub(/^[ \t]+|[ \t]+$/,""); sid=$0 }
      /^files:/ { sub(/^files:[ \t]*/,""); gsub(/^\[|\]$/,"")
                  n=split($0,a,","); for(i=1;i<=n;i++){gsub(/^[ \t]+|[ \t]+$/,"",a[i]); if(a[i]!="") paths=paths (paths==""?"":"\x01") a[i]} }
      END { if (sid!="") printf "%s\t%s\n", sid, paths }
    ' "$f"
  done > "$FILESMAP"

  awk -v want="$plan" -v epic="$epic" -F '\t' "
$AWK_COMMON
"'
  # second file: id \t path\x01path…
  FILENAME==ARGV[2] { fmap[$1]=$2; next }
  END {
    for (i=1;i<=N;i++) {
      if (plan[i]!=want || ep[i]!=epic) continue
      if (stt[i]=="DONE" || stt[i]=="SKIP") continue
      scope[++ns]=i
    }
    if (ns==0) { printf "Epic %s — nothing to build: every story is DONE or SKIP.\n", epic; exit }

    # Dependency levels: wave 1 = blockers all DONE (or empty); wave k+1 = blockers
    # DONE or scheduled in an earlier wave. Fixpoint, so a cycle simply never schedules.
    for (r=1; r<=ns; r++) {
      progressed=0
      for (x=1;x<=ns;x++) { i=scope[x]
        if (id[i] in lvl) continue
        okv=1; h=""
        if (stt[i]!="BUG" && blk[i]!="" && blk[i]!="-") {
          n=split(blk[i],a,",")
          for (j=1;j<=n;j++) { b=trim(a[j]); if (b=="") continue
            if (st[b]=="DONE") continue
            # A blocker scheduled in an EARLIER wave is satisfied by the time this one
            # dispatches; one scheduled in the wave being filled right now is not —
            # `lvl[b] < r`, never `b in lvl`, or a story lands beside its own blocker.
            if ((b in lvl) && lvl[b] < r) continue
            okv=0; h = h (h==""?"":", ") b }
        }
        hold[id[i]]=h
        if (okv) { lvl[id[i]]=r; progressed=1; if (r>depth) depth=r }
      }
      if (!progressed) break
    }

    # Split each dependency level so no two stories in one wave share a declared path.
    w=0
    for (r=1; r<=depth; r++) {
      delete claimed
      while (1) {
        any=0
        w++
        for (x=1;x<=ns;x++) { i=scope[x]
          if (lvl[id[i]]!=r || (id[i] in wave)) continue
          conflict=""
          m=split(fmap[id[i]], pp, "\x01")
          for (k=1;k<=m;k++) { if (pp[k]=="") continue
            key = w "\x01" pp[k]
            if (key in claimed) { conflict=pp[k]; break } }
          if (conflict!="") continue
          for (k=1;k<=m;k++) if (pp[k]!="") claimed[w "\x01" pp[k]]=1
          wave[id[i]]=w; wcount[w]++; any=1
        }
        if (!any) { w--; break }
        # anything left at this level needs another wave
        left=0
        for (x=1;x<=ns;x++) { i=scope[x]; if (lvl[id[i]]==r && !(id[i] in wave)) left=1 }
        if (!left) break
      }
    }
    nwaves=w

    unsched=0
    for (x=1;x<=ns;x++) { i=scope[x]; if (!(id[i] in wave)) unsched++ }

    if (nwaves==0) {
      printf "Epic %s — un-startable: no story has all its blockers DONE.\n\n", epic
      for (x=1;x<=ns;x++) { i=scope[x]; if (hold[id[i]]!="") printf "  %s  %s   ← waiting on %s\n", id[i], ttl[i], hold[id[i]] }
      exit
    }

    printf "Epic %s — Wave plan (%d stor%s, depth %d):\n\n", epic, ns-unsched, ((ns-unsched)==1?"y":"ies"), nwaves
    for (k=1;k<=nwaves;k++) {
      shape = (wcount[k]>1) ? "(parallel)" : "(solo)"
      first=1
      for (x=1;x<=ns;x++) { i=scope[x]
        if (wave[id[i]]!=k) continue
        lbl = first ? sprintf("  Wave %-2d %-11s", k, shape) : sprintf("  %-19s", "")
        need = ""
        if (blk[i]!="" && blk[i]!="-") {
          n=split(blk[i],a,","); for (j=1;j<=n;j++) { b=trim(a[j]); if (b!="" && st[b]!="DONE") need = need (need==""?"":", ") b }
        }
        row = sprintf("%s %-6s %-24s %s", lbl, id[i], ttl[i], sz[i])
        if (need!="") row = row "   ← needs " need
        if (stt[i]=="BUG") row = row "   🐛 Bug-Fix Mode"
        print row
        first=0
      }
    }
    if (unsched) {
      print "\nUNSCHEDULABLE (excluded — blocker never resolves):"
      for (x=1;x<=ns;x++) { i=scope[x]; if (!(id[i] in wave)) printf "  %s  %s   ← waiting on %s\n", id[i], ttl[i], hold[id[i]] }
    }
    if (nwaves>3) printf "\nNote: %d waves means %d sequential merge+dispatch cycles — heavy token use. Consider re-scoping.\n", nwaves, nwaves
    printf "\nPLAN: %s\n", want
  }' "$TSV" "$FILESMAP"
  rm -f "$FILESMAP"
}

# ------------------------------------------------------------------- run ------
load_rows > "$TSV"

case "$MODE" in
  state) render_state ;;
  waves) render_waves "$EPIC_ARG" ;;
  next)  render_next "$PLAN_ARG" ;;
  status|progress)
    PLANS=$(list_plans)
    if [ -n "$PLAN_ARG" ]; then PLANS="$PLAN_ARG"; fi
    NPLANS=$(printf '%s\n' "$PLANS" | grep -c . || true)
    if [ "$NPLANS" -eq 0 ]; then
      echo "No task plans found in tasks/."
      echo "Run /ck-code:plan to generate epics and stories first."
      exit 0
    fi
    if [ "$NPLANS" -gt 1 ]; then
      echo "## Project Plans Found"
      echo
      i=0
      while IFS= read -r p; do
        [ -n "$p" ] || continue
        i=$((i+1))
        printf '%d. %s/ — %s\n' "$i" "$p" "$(plan_name "$p")"
      done <<<"$PLANS"
      echo
      echo "Showing: ALL plans"
      echo
    fi
    first=1
    while IFS= read -r p; do
      [ -n "$p" ] || continue
      [ "$first" -eq 1 ] || echo
      first=0
      if [ "$MODE" = "status" ]; then render_status "$p"; else render_progress "$p"; fi
    done <<<"$PLANS"
    ;;
esac
