#!/usr/bin/env bash
# ck-code SessionStart hook.
#   (1) Reload skills so experts/guides generated by /ck-code:team become
#       invocable in the same session — no restart required.
#   (2) Inject a one-line workflow summary aggregated across every plan's
#       STORIES_INDEX.md, and a migration notice when the project is pre-v6.
#
# Best-effort by design: this must NEVER fail or block session startup, so it
# avoids `set -e` and swallows every probe error. Output is a single JSON line.
# JSON is assembled with a proper string escape (no raw interpolation) so a path
# containing a quote or backslash cannot produce invalid JSON.

# json_escape — escape a string for embedding in a JSON double-quoted value.
json_escape() {
  printf '%s' "$1" | awk '
    BEGIN{ORS=""}
    { gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); gsub(/\t/,"\\t"); print }
    NR>1{ }
  ' | tr '\n' ' '
}

emit() { # emit CONTEXT_STRING
  local esc; esc=$(json_escape "$1")
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true,"additionalContext":"%s"}}\n' "$esc"
}
emit_plain() {
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true}}\n'
}

# No tasks/ at all → nothing to summarise.
[ -d tasks ] || { emit_plain; exit 0; }

# Pre-v6 detection: a project with tasks/ content but no `layout: v6` stamp.
# LAYOUT must track references/version-gate.md — a stale value here nags every
# correctly-stamped project on every session start.
LAYOUT=v6
layout=""
[ -f tasks/VERSION.md ] && layout=$(awk -F: '/^layout:/{gsub(/[ \t]/,"",$2);print $2;exit}' tasks/VERSION.md 2>/dev/null)
has_plan=$(ls tasks/*/STORIES_INDEX.md tasks/*/epics 2>/dev/null | head -1)

if [ -n "$has_plan" ] && [ "$layout" != "$LAYOUT" ]; then
  emit "ck-code detected a pre-$LAYOUT project layout. Run /ck-code:migrate to upgrade it (one-shot, safe) before using design/plan/build/fix."
  exit 0
fi

# Re-stamp the informational `ck-code:` line.
#
# The gate compares `layout:` alone; `ck-code:` records which plugin version last
# touched the project. Leaving it to "each skill may optionally restamp" made it
# nobody's job, so a project stamped at 6.0.0 stayed there through every release.
# A session start IS "the first run after a plugin update", so it happens here:
# no model tokens, no tool call, and never before the v6 check above has passed.
#
# It only ever REWRITES an existing stamp. Creating one is the version gate's job —
# a stamp written here would mark an unmigrated project as clean.
RESTAMPED=""
restamp() {
  [ "$layout" = "$LAYOUT" ] || return 0
  [ -f tasks/VERSION.md ] && [ -w tasks/VERSION.md ] || return 0
  local pj running cur tmp
  pj="$(dirname "$0")/../.claude-plugin/plugin.json"
  [ -f "$pj" ] || return 0
  running=$(awk -F'"' '/"version"[[:space:]]*:/{print $4; exit}' "$pj" 2>/dev/null)
  # Anything that is not a bare dotted number is not a version — leave the file alone.
  case "$running" in ""|*[!0-9.]*) return 0 ;; esac
  cur=$(awk -F: '/^ck-code:/{gsub(/[ \t]/,"",$2); print $2; exit}' tasks/VERSION.md 2>/dev/null)
  [ "$cur" = "$running" ] && return 0
  tmp="tasks/.VERSION.md.$$"
  awk -v v="$running" '
    /^ck-code:/      { if (!seen) { print "ck-code: " v; seen=1 } ; next }
    /^layout:/ && !seen { print "ck-code: " v; seen=1 }
    { print }
  ' tasks/VERSION.md > "$tmp" 2>/dev/null && cat "$tmp" > tasks/VERSION.md 2>/dev/null
  rm -f "$tmp"
  RESTAMPED="${cur:-unstamped} → $running"
}
restamp

# Current-layout project: aggregate story counts across ALL plans (Status is the 5th
# |-field, Delivery the 6th). ck-index.sh escapes a literal pipe in a title as `\|`;
# splitting on a bare `|` would count that as a column and read the wrong field, so
# neutralise it first.
#
# The Delivery tally is the merge probe. A row reading `PR #<n>` has an anchor GitHub
# may already have merged, and nothing in ck-code observes a merge as it happens — so
# the count is surfaced here and reconciled by `ck-project sync`. This stays a LOCAL
# read of a generated file: a hook that called the network would delay every session
# start and fail on an unauthenticated machine.
counts=$(awk '
  FNR==1{next}
  {
    line=$0; gsub(/\\\|/,"\001",line)
    n=split(line,f,"|")
    if (n>=7) {
      s=f[5]; gsub(/^[ \t]+|[ \t]+$/,"",s)
      if(s=="TODO")todo++; else if(s=="IN PROGRESS")ip++; else if(s=="DONE")done++; else if(s=="BUG")bug++
      d=f[6]; gsub(/^[ \t]+|[ \t]+$/,"",d)
      if(d ~ /^PR/) pend++
    }
  }
  END{ printf "%d %d %d %d %d", todo, ip, done, bug, pend }
' tasks/*/STORIES_INDEX.md 2>/dev/null)

if [ -n "$counts" ]; then
  set -- $counts
  todo=${1:-0}; ip=${2:-0}; done=${3:-0}; bug=${4:-0}; pend=${5:-0}
  # All-zero means the indexes carry no story rows — say nothing rather than
  # emit a vacuous "0 TODO, 0 IN PROGRESS, 0 DONE".
  if [ $((todo + ip + done + bug)) -eq 0 ]; then
    if [ -n "$RESTAMPED" ]; then emit "ck-code updated: $RESTAMPED (tasks/VERSION.md restamped)."; else emit_plain; fi
    exit 0
  fi
  msg="ck-code project: $todo TODO, $ip IN PROGRESS, $done DONE"
  [ "${bug:-0}" -gt 0 ] && msg="$msg, $bug BUG"
  msg="$msg. Run /ck-code:track for the next step."
  [ "${pend:-0}" -gt 0 ] && msg="$msg $pend awaiting merge confirmation — run 'ck-project sync' to reconcile them, or /ck-code:ship, which syncs first."
  # Named rather than silent: the restamp is a one-line change to a tracked file, so the
  # user should learn it from here and not from an unexplained diff in `git status`.
  [ -n "$RESTAMPED" ] && msg="$msg ck-code updated: $RESTAMPED (tasks/VERSION.md restamped)."
  emit "$msg"
elif [ -n "$RESTAMPED" ]; then
  emit "ck-code updated: $RESTAMPED (tasks/VERSION.md restamped)."
else
  emit_plain
fi
