#!/usr/bin/env bash
# ck-code SessionStart hook.
#   (1) Reload skills so experts/guides generated by /ck-code:team become
#       invocable in the same session — no restart required.
#   (2) Inject a one-line workflow summary aggregated across every plan's
#       STORIES_INDEX.md, and a migration notice when the project is pre-v5.
#
# Best-effort by design: this must NEVER fail or block session startup, so it
# avoids `set -e` and swallows every probe error. Output is a single JSON line.
# JSON is assembled with a proper string escape (no raw interpolation) so a path
# containing a quote or backslash cannot produce invalid JSON.

# json_escape — escape a string for embedding in a JSON double-quoted value.
json_escape() {
  printf '%s' "$1" | awk '
    BEGIN{ORS=""}
    { gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); gsub(/\t/,"\\t"); print }
    NR>1{ }
  ' | tr '\n' ' '
}

emit() { # emit CONTEXT_STRING
  local esc; esc=$(json_escape "$1")
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true,"additionalContext":"%s"}}\n' "$esc"
}
emit_plain() {
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true}}\n'
}

# No tasks/ at all → nothing to summarise.
[ -d tasks ] || { emit_plain; exit 0; }

# Pre-v5 detection: a project with tasks/ content but no `layout: v5` stamp.
# LAYOUT must track references/version-gate.md — a stale value here nags every
# correctly-stamped project on every session start.
LAYOUT=v5
layout=""
[ -f tasks/VERSION.md ] && layout=$(awk -F: '/^layout:/{gsub(/[ \t]/,"",$2);print $2;exit}' tasks/VERSION.md 2>/dev/null)
has_plan=$(ls tasks/*/STORIES_INDEX.md tasks/*/epics 2>/dev/null | head -1)

if [ -n "$has_plan" ] && [ "$layout" != "$LAYOUT" ]; then
  emit "ck-code detected a pre-$LAYOUT project layout. Run /ck-code:migrate to upgrade it (one-shot, safe) before using design/plan/build/fix."
  exit 0
fi

# Current-layout project: aggregate story counts across ALL plans (Status is the 5th
# |-field). ck-index.sh escapes a literal pipe in a title as `\|`; splitting on a bare
# `|` would count that as a column and read the wrong field, so neutralise it first.
counts=$(awk '
  FNR==1{next}
  {
    line=$0; gsub(/\\\|/,"\001",line)
    n=split(line,f,"|")
    if (n>=6) {
      s=f[5]; gsub(/^[ \t]+|[ \t]+$/,"",s)
      if(s=="TODO")todo++; else if(s=="IN PROGRESS")ip++; else if(s=="DONE")done++; else if(s=="BUG")bug++
    }
  }
  END{ printf "%d %d %d %d", todo, ip, done, bug }
' tasks/*/STORIES_INDEX.md 2>/dev/null)

if [ -n "$counts" ]; then
  set -- $counts
  todo=${1:-0}; ip=${2:-0}; done=${3:-0}; bug=${4:-0}
  # All-zero means the indexes carry no story rows — say nothing rather than
  # emit a vacuous "0 TODO, 0 IN PROGRESS, 0 DONE".
  if [ $((todo + ip + done + bug)) -eq 0 ]; then
    emit_plain
    exit 0
  fi
  msg="ck-code project: $todo TODO, $ip IN PROGRESS, $done DONE"
  [ "${bug:-0}" -gt 0 ] && msg="$msg, $bug BUG"
  msg="$msg. Run /ck-code:track for the next step."
  emit "$msg"
else
  emit_plain
fi
