#!/usr/bin/env bash
# ck-code SessionStart hook.
#   (1) Reload skills so experts/guides generated by /ck-code:team become
#       invocable in the same session — no restart required.
#   (2) Inject a one-line workflow summary aggregated across every plan's
#       STORIES_INDEX.md, and a migration notice when the project is pre-v4.
#
# Best-effort by design: this must NEVER fail or block session startup, so it
# avoids `set -e` and swallows every probe error. Output is a single JSON line.
# JSON is assembled with a proper string escape (no raw interpolation) so a path
# containing a quote or backslash cannot produce invalid JSON.

# json_escape — escape a string for embedding in a JSON double-quoted value.
json_escape() {
  printf '%s' "$1" | awk '
    BEGIN{ORS=""}
    { gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); gsub(/\t/,"\\t"); print }
    NR>1{ }
  ' | tr '\n' ' '
}

emit() { # emit CONTEXT_STRING
  local esc; esc=$(json_escape "$1")
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true,"additionalContext":"%s"}}\n' "$esc"
}
emit_plain() {
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","reloadSkills":true}}\n'
}

# No tasks/ at all → nothing to summarise.
[ -d tasks ] || { emit_plain; exit 0; }

# Pre-v4 detection: a project with tasks/ content but no `layout: v4` stamp.
layout=""
[ -f tasks/VERSION.md ] && layout=$(awk -F: '/^layout:/{gsub(/[ \t]/,"",$2);print $2;exit}' tasks/VERSION.md 2>/dev/null)
has_plan=$(ls tasks/*/STORIES_INDEX.md tasks/*/epics 2>/dev/null | head -1)

if [ -n "$has_plan" ] && [ "$layout" != "v4" ]; then
  emit "ck-code detected a pre-v4 project layout. Run /ck-code:migrate to upgrade it (one-shot, safe) before using design/plan/build/fix."
  exit 0
fi

# v4 project: aggregate story counts across ALL plans (Status is the 5th |-field).
counts=$(awk -F'|' '
  FNR==1{next}
  NF>=6 {
    s=$5; gsub(/^[ \t]+|[ \t]+$/,"",s)
    if(s=="TODO")todo++; else if(s=="IN PROGRESS")ip++; else if(s=="DONE")done++; else if(s=="BUG")bug++
  }
  END{ printf "%d %d %d %d", todo, ip, done, bug }
' tasks/*/STORIES_INDEX.md 2>/dev/null)

if [ -n "$counts" ]; then
  set -- $counts
  todo=${1:-0}; ip=${2:-0}; done=${3:-0}; bug=${4:-0}
  msg="ck-code v4 project: $todo TODO, $ip IN PROGRESS, $done DONE"
  [ "${bug:-0}" -gt 0 ] && msg="$msg, $bug BUG"
  msg="$msg. Run /ck-code:track for the next step."
  emit "$msg"
else
  emit_plain
fi
